### ISSUE TITLE
Soundpack crash to desktop

### ISSUE THREAD

**Issue by Shackram** [cataclysmbnteam/Cataclysm-BN#101]
# Describe the bug

Game crashes if when trying to use a soundpack from CDDA. I've tried RRF, @ and Otopack, pasting the folders into data/sounds as usual.

The game launches normaly, music plays on the main menu and when i load on the map, but crashes to desktop as soon as i take a step.

It's not clear to me if this is a case of soundpacks needing to be changed to work with CBN, something that CBN has to fix to let them work or even something weird going on on my end. So i'm opening this issue because i couldn't find anything useful about this.

# Steps To Reproduce

1. Install and enable soundpack
2. Create new map and character
3. Load into map
4. Take a step
5. Crash to desktop

# Expected behavior

Game plays the soundpack sounds and doesn't crash.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 1ab150f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

# Additional context

The game crashes to desktop but doesn't generate a crash.log file. Debug.log has some stuff that seem to be related.

[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5360499/debug.log)

**Comment by Firestorm01X2** [comment]
@Shackram Thank you for attaching logs.
For now I could not repsoduce crash with Win x64 with both soundpacks. Crash didn't heppen for me after loading.
There I've found:
`src/sdlsound.cpp:148: Failed to load audio file data/sound/damalsksoundpack-0.2/music/Dreaming with Great Old One (Arkham Radio Podcast).mp3: Unrecognized audio format`

What is `damalsksoundpack-0.2`?

Still could you try to reprodcue it on your machine witn fresh version and fresh directory that is guranteed clean from any other mods and spound packs?

**Comment by Shackram** [comment]
@Firestorm01X2 Hey, thanks for the reply.

damalsksoundpack-0.2 is the folder name of [@'s soundpack](https://discourse.cataclysmdda.org/t/soundpack-s-soundpack-vehicle-sounds-licensed-music-and-more/20131)

The previous test was done with a fresh directory, i've created another fresh directory and tested again, but this time using RRFSounds. Crashed again when i took the first step. Again didn't generate a crash.log [CBN debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5361626/debug.log)

I also went and got the latest experimental version of CDDA, tried that with @'s pack in a fresh directory and it worked fine, i'll attach that debug.log just in case. [CDDA debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5361641/debug.log)

**Comment by Firestorm01X2** [comment]
@Shackram Thank you for exta logs. Does it happens for you with default soundpack (ie no soundpack)?

**Comment by Shackram** [comment]
@Firestorm01X2 No, it works fine with the default soundpack.

**Comment by Shackram** [comment]
@Firestorm01X2  Alright, i have some news. 

Cataclysm BN doesn't like my Corsair headset in some way. I use a H60 headset, it jacks into a an USB dongle with it's own audio driver and that seems to be what BN is having problems with.

With the dongle plugged, the game crashes every time. I also updated the drivers as ICUE had an update available, but that didn't help.

If i unplug the dongle and plug the headset jack onto the motherboard audio, the game doesn't crash and the soundpacks work as expected. I can't use the headset mic that way, but it's a workaround to get sounds working in CBN for now.

I've used this headset for a few years now and never had problems on CDDA

![H60 Dongle Driver](https://user-images.githubusercontent.com/35645664/96356581-e535a800-10c6-11eb-90ff-9f583b9742ca.PNG)

**Comment by Firestorm01X2** [comment]
> 
> 
> @Firestorm01X2 Alright, i have some news.

Thank you for report!
From my side- I din'n't manage to find similar issue or fix from DDA. Maybe I need to look further.

Still I've nocied that BN  and DDA using slighly different version of SDL.

CBN
14:54:13.687 INFO : SDL version used during compile is 2.0.9
14:54:13.687 INFO : SDL version used during linking and in runtime is 2.0.9

CDDA
15:05:02.618 INFO : SDL version used during compile is 2.0.5
15:05:02.618 INFO : SDL version used during linking and in runtime is 2.0.5

**Comment by Firestorm01X2** [comment]
Looks like this bug is tricky to reproduce. One anonymous user tried to catch in various ways. No luck for now.

Мимоанон, хотел помочь, но вряд ли выйдет.
Вот что имею, на текущий момент. Если кратко, то звук и музыка на всех настройках вывода звука есть.
Win10 Pro, x64, катаБН последняя из шапки, тайлсет деда и отопак тоже последние свежескачанные.
Как проверял-
1. Как обычно - вывод звука на телевизор а телевизор на колонки с сабом через миниджек через HDMI, звуки/музыка есть, крашей нет;
2. Через проводные наушники с микрофоном, подключены на заднюю панель компа, аналогично без проблем;
3. Извратился по полной - есть обычный юсб блютуз, есть дешёвая китайская гарнитура пятилетней давности вида EX-01, законнектил, звук вывел, в кате так же звук на ухо, звуки/музыка есть, крашей нет.
Сделал все возможные тесты обычного запуска и игры, проблем не обнаружил.
В логе дебага ничего интересного на мой взгляд нет, все три лога одинаковые. Если что-то нужно ещё - постараюсь проверить 

===
Mimoanon, I wanted to help, but it’s unlikely.
Here's what I have at the moment. In short, there is sound and music on all sound output settings.
Win10 Pro, x64, kataBN is the last of the caps, grandfather's tileset and otpak are also the latest freshly downloaded.
How tested-
1. As usual - sound output to TV and TV to speakers with sub via minijack via HDMI, there are sounds / music, no crashes;
2. Through wired headphones with a microphone, connected to the back of the computer, similarly without problems;
3. I got twisted to the fullest - there is a regular bluetooth bluetooth, there is a cheap Chinese headset of five years old type EX-01, it is legitimate, the sound was brought out, there is also a sound in the ear in the cat, there are sounds / music, no crashes.
I did all possible tests of a normal launch and game, I did not find any problems.
In my opinion, there is nothing interesting in the debug log, all three logs are the same. If you need something else, I'll try to check

**Comment by olanti-p** [comment]
> I didn't manage to find similar issue or fix from DDA.

> Still I've noticed that BN and DDA using slighly different version of SDL.
> 
> CBN
> 14:54:13.687 INFO : SDL version used during compile is 2.0.9
> 14:54:13.687 INFO : SDL version used during linking and in runtime is 2.0.9
> 
> CDDA
> 15:05:02.618 INFO : SDL version used during compile is 2.0.5
> 15:05:02.618 INFO : SDL version used during linking and in runtime is 2.0.5

SDL 2.0.6 changed default audio driver on Windows to WASAPI, deprecating previously used XAudio2:
https://discourse.libsdl.org/t/sdl-2-0-6-released/23109

The following releases state that they 'contain bugfixes', so updating to the latest 2.0.12 might help.
Also, it looks like it's possible to specify audio driver to use ([link](https://wiki.libsdl.org/FAQUsingSDL)) - could be worthwhile to try something other than WASAPI

**Comment by Firestorm01X2** [comment]
@Shackram , hello.
 olanti-p compiled game for testing with updayed SDL: 
https://github.com/olanti-p/Cataclysm-DDA/releases/tag/26
Could you, please, try it out? It may fix issue for you.

**Comment by ROMB** [comment]
Hi. I've got exactly the same issue with CTD, using USB headset (Logitech G933).
Using [@'s soundpack](https://discourse.cataclysmdda.org/t/soundpack-s-soundpack-vehicle-sounds-licensed-music-and-more/20131), game CDS after 1-2 moves, probably caused by step sounds.
Last line of [debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5903325/debug.log) is
```
src/sdlsound.cpp:499: Failed to play sound effect: Unsupported audio channels
```
Running version posted by @Firestorm01X2 I get [crash.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5903330/crash.log)

**Comment by Coolthulhu** [comment]
Seems that MXE has updated their SDL version.
In https://travis-ci.org/github/cataclysmbnteam/Cataclysm-BN/jobs/757903496:
```
Get:59 https://mirror.mxe.cc/repos/apt xenial/main amd64 mxe-i686-w64-mingw32.static-sdl2 amd64 2.0.14-xenial-build-2021-01-10 [3,247 kB]
Get:65 https://mirror.mxe.cc/repos/apt xenial/main amd64 mxe-i686-w64-mingw32.static-sdl2-mixer amd64 2.0.4-xenial-build-2021-01-10
```

In https://pkg.mxe.cc/pkg/:
```
SDL2-2.0.14.tar.gz                                 01-Feb-2021 16:01             6089974
SDL2_mixer-2.0.4.tar.gz                            01-Feb-2021 16:08            11125077
```

Would be useful if someone who had the crash re-tested it with a new (Windows) CBN version.

**Comment by Mitchs98** [comment]
[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5963842/debug.log)
Have this issue myself running the very latest CBN version. Updated it just a few moments ago to test it out. 

Appears to be an SDL error. Really hoping there's a way to fix it. Won't produce a crashlog, however, it produced the debug log.

**Comment by Firestorm01X2** [comment]
> 
> 
> [debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5963842/debug.log)
> Have this issue myself running the very latest CBN version. Updated it just a few moments ago to test it out.
> 
> Appears to be an SDL error. Really hoping there's a way to fix it. Won't produce a crashlog, however, it produced the debug log.

In log I see crash after DeadPeople Tileset

> 02:33:05.042 INFO : Loaded tileset: UNDEAD_PEOPLE_BASE
> 02:34:21.376 ERROR SDL : (error message will follow backtrace)

Try to swith to other tileset or another renderer

**Comment by Mitchs98** [comment]
[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5967116/debug.log)
Tried all the renderers and the Retrodays+ tileset once. Error seems entirely SDL/Soundpack related.

**Comment by Mitchs98** [comment]
So far #355 seems to have fixed crashing with a soundpack. Currently playing with Otopack enabled just fine, haven't gotten into any combat but generally moving around doesn't crash the game anymore.
