### ISSUE TITLE
Android version cannot be started

### ISSUE THREAD

**Issue by Fruitybite** [cataclysmbnteam/Cataclysm-BN#1149]
# Describe the bug
Android refuses to start BN (7835dd3 and fe46d08)

# Steps To Reproduce
1. Download BN apk, version 7835dd3 or fe46d08
2. After "installing game data..." message, the game suddenly crashes and kicks me back to home screen

# Expected behavior
It should work well like old version, for example 9c859b0.

# Screenshots

# Versions and configuration
- OS: Android 11
- Game Version: 7835dd3 and fe46d08
- Graphics version: Tiles
- Ingame language: Korean
- Mods loaded: BN only

# Additional context
First I found this after updating from old version so I thought some kind of old data trash caused this, but Uninstalling & Re-Installing didn't work.
Not sure about this might happen in other OS version.

**Comment by olanti-p** [comment]
Can reproduce.
Probably caused by runner update from [20211114.1](https://raw.githubusercontent.com/actions/virtual-environments/ubuntu20/20211114.1/images/linux/Ubuntu2004-README.md) to [20211122.1](https://raw.githubusercontent.com/actions/virtual-environments/ubuntu20/20211122.1/images/linux/Ubuntu2004-README.md), since nothing in #1118 looks like it should cause problems, and clean install of 7835dd3 works fine on Windows.

**Comment by olanti-p** [comment]
The runner has been updated again, to [20211129.1](https://raw.githubusercontent.com/actions/virtual-environments/ubuntu20/20211129.1/images/linux/Ubuntu2004-README.md), and the issue seems to have fixed itself starting with version d46f29593ea57fb3c9bd7f276e372c0731235a9b.
Not sure what's up with that.

**Comment by Fruitybite** [comment]
Just checked and it's really fixed... I'll close this now :)
