### ISSUE TITLE
Zombies quantum tunneling through armored vehicles when turning them: a bug as old as DDA

### ISSUE THREAD

**Issue by tyrael93** [cataclysmbnteam/Cataclysm-BN#116]
We all know this one. 
Is it ever going to get fixed?

**Comment by MrOlaf** [comment]
Well there are a couple of possible solutions: 1) disallow diagonal movement for all creatures, 2) change the driving model to disallow creature movement on any tile if a vehicle has an engine running, 3) leave AS IS because above fixes impact the sandboxiness of the user experience. BTW: died yesterday to a rotweiler hitchiking into my steamroller on an ultra-low hp run.

**Comment by Coolthulhu** [comment]
Fixing this properly would require either some new, clever design or taking a massive performance hit.
```
a/
/b
```
In order to detect the wall-phasing movement from `a` to `b`, two more tiles have to be checked.
This would be tolerable if it only needed to be checked on movement, but it also needs to cover vision, which is expensive and would require a big rewrite of many parts of the game.

It could be doable if it only covered specific actions, like movement, attack, ranged trajectory, but then every such action would need to be specifically handled.

**Comment by DrPariah** [comment]
I kinda like it, in a way. It puts a little threat into driving, and it gives Mad Max visions of zombies jumping on your vehicle and forcing their way inside. 
--
Sent from myMail for Android Monday, 19 October 2020, 10:38AM -05:00 from MrOlaf  notifications@github.com :

**Comment by MrOlaf** [comment]
> I kinda like it, in a way. It puts a little threat into driving, and it gives Mad Max visions of zombies jumping on your vehicle and forcing their way inside. -- Sent from myMail for Android Monday, 19 October 2020, 10:38AM -05:00 from MrOlaf 

This is also a good point. Zeds can't drop through your roof or windows, so I find that the imperfections of the current system is actually a fine solution until somebody figures out how to use those sweet 6-12 physical cores CPUs in the game without rewriting the code from scratch.

**Comment by tyrael93** [comment]
Ah dang, I'd have expected it to be not so simple a fix.
I remember double-layering with " tiles completely fixed the problem, while single-layering had the same effect as regular / | tiles. Would switching the default tile sign to = instead of |/ help? I mean, it's not /as/ good as | but it's a frame tile option already (and the vast majority of players nowadays uses tiles anyway so they wouldn't notice)

**Comment by kevingranade** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/42462

**Comment by tyrael93** [comment]
![Don't](https://user-images.githubusercontent.com/5557920/97554737-7bc36c80-19d7-11eb-9573-42fcdbf1be69.png)
