### ISSUE TITLE
Please revert the Telescopic Eyes so they no longer remove (beneficial) ocular mutations.

### ISSUE THREAD

**Issue by PsyXypher** [cataclysmbnteam/Cataclysm-BN#1190]
# Is your feature request related to a problem? Please describe.
This is, simply put, not a fair trade. While it does make sense, as the CBM explicitly replaces your inner eye, this is in gameplay terms not a fair or feasible trade. 

Night Vision and its upgrades are powerful, to the point where people suggest it to new players. Originally, the CBM did not remove beneficial mutations, and instead would remove far-sighted and near sighted. The Telescopic Eyes CBM is in effect, an inbuilt pair of Binoculars, and can be replaced with a 0.25 Volume item (the Survivor Telescope). 

# Describe the solution you'd like
Revert the Telescopic Eyes CBM so it uses its original function of removing negative sight mutations while keeping other in place.

**Comment by Proxiehunter** [comment]
Balance wise I don't see an issue with the player being allowed to retain ocular mutations. Lore wise there's not really a reason that telescopic eyes should require altering the inner eye rather than being bolted to the skull and pivoting over the eye when telescopic vision is desired. I'm sure there are other possible ways of describing the cybernetic that don't require it to replace the eye itself allowing players to have the implant and keep eye mutations.

**Comment by Soadreqm** [comment]
I think the idea is that you only get the bionic if you have negative eye mutations. If you have amazing night vision and +3 perception, then there's nothing stopping you from leaving your eyes intact and using the 0.25 liter telescope instead.

**Comment by chaosvolt** [comment]
One added complication here is that that mods that add any other eye-related mutations are unable to have it properly interact with this CBM's effects. So restricting the CBM to only blocking a specific selection of eye-related mutations would also make that inconsistency stand out less (unless they're trying to find some way to hack in new forms of vision impairment, in which case they're still going to have this problem).

**Comment by Roet718** [comment]
Also id like to point out that the telescopic eyes cbm is not removable (gives a message saying it would make you blind) so installing it permanently locks the player out of vision-related mutations without any indication that it will do so when you install it.

**Comment by chaosvolt** [comment]
Smol lore note that came up after some DMs with someone who'd been involved in the original change to telescopic eyes: from a realism perspective, flavoring the CBM as primarily an artificial form of corrective lens, either implanted over the natural lens or as an outright replacement, would justify fixing the main pre-cataclysm vision traits with little impact on night vision mutations or most other post-cataclysm vision-related mutations.

Basically, both far-sightedness and near-sightedness are conditions primarily involving the lenses rather than the retinas or other parts of the eye, and thus an implant that replaces the natural lenses with artificial ones could logically fix focus issues of that soirt. Meanwhile, night vision mutations would entail changes to the types of receptive cells, to the retina, the development of a tapetum lucidum, etc. All stuff that involves the back of the eye, basically.
