### ISSUE TITLE
strange lags in specific place

### ISSUE THREAD

**Issue by DZiral** [cataclysmbnteam/Cataclysm-BN#1322]
# Describe the bug
Strange game lags during movent. It happens only in specific place in my save (pool and southern house). Other places are ok. Save attached. 
I am unsure if it my save problem or some game bug. Feell free to close this if not bug. Thanks

# Steps To Reproduce

1. Load my save (sherry/misato)
2. Hold move button. Left or right for example. After moving about ten tiles game freezes for small time. Look like some heavy calculation happens. 
This happens only if I move near pool/house south of the pool.

# Expected behavior

Normal movement as in other places (without periodic lags).

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0a8096c [64-bit]
- Graphics Version: Tiles
- Game Language:  [Russian]
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    No Fungal Monsters [No_Fungi],
    Aftershock [aftershock],
    No Filthy Clothing [no_filthy_clothing],
    Manual Bionic Installation [manualbionicinstall],
    Prevent Zombie Revivication [no_reviving_zombies]
]
[save.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/8018240/save.zip)

**Comment by olanti-p** [comment]
Looks like the mall nearby has an enormous electric grid that costs a lot to re-calculate on submap shift. Leaving mall entirely beyond reality bubble immediately gets rid of the lag.
![image](https://user-images.githubusercontent.com/60584843/152863354-0d9276ec-f1e5-42ec-b4db-6add1fc7ce50.png)
![image](https://user-images.githubusercontent.com/60584843/152864254-31261bb6-c3d9-4cbe-8594-3f0bab95e1f8.png)

**Comment by Coolthulhu** [comment]
Looks like it's time to start keeping the grids between map shifts. I wrote grids without it, because I didn't expect the costs to get so high.

I don't get the profiling results.
* Why is most of the time spent adding tripoint-equivalents together? It looks as if it was trying to copy `six_cardinal_directions` or something similarly expensive.
* Why are `std::queue::pop()` and `std::queue::empty()` so expensive?
* How is it possible that `std::set::emplace()` is cheaper than any of the above?

`std::queue` is supposed to be using `std::deque` by default and `std::deque` is supposed to guarantee `O(1)` push, pop and size.

**Comment by olanti-p** [comment]
VS2022 profiler seems to be having trouble with VS2019 toolchain, here's results from VS2019:
![image](https://user-images.githubusercontent.com/60584843/153005766-ae5d7213-2fb9-4fdc-b5c1-49b474347135.png)
