### ISSUE TITLE
AoE Washing machine

### ISSUE THREAD

**Issue by Allmyusualnamesaretaken** [cataclysmbnteam/Cataclysm-BN#147]
# Is your feature request related to a problem? Please describe.
At present, you can only wash filthy clothing/miscellany that is in your inventory, which makes doing large loads kind of tedious.

# Describe the solution you'd like
Can we use washing kits and the like on all filthy items within the crafting radius of 6 tiles or so?

# Describe alternatives you've considered
Alternatively, would be a substantial QoL improvement if we could wash filthy articles on the same tile as us at least.

# Additional context
![art](https://user-images.githubusercontent.com/49605446/97241538-d2f2f280-17c7-11eb-9ac6-9bba86dd2f48.png)

**Comment by Night-Pryanik** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/45348

**Comment by Firestorm01X2** [comment]
> 
> 
> [CleverRaven#45348](https://github.com/CleverRaven/Cataclysm-DDA/pull/45348)

Thank you. But implementing it directy gives me:
ERROR : D:\gitreps\Cataclysm-BN\src\visitable.cpp:59 [find_parent] Tried to find item parent using an object that doesn't contain it
while trying to wash. So there is definitely more.

**Comment by olanti-p** [comment]
> But implementing it directy gives me:
> `ERROR : D:\gitreps\Cataclysm-BN\src\visitable.cpp:59 [find_parent] Tried to find item parent using an object that doesn't contain it`
> while trying to wash.

There were 2 problems:
1. `inventory_multiselector` UI that's responsible for selecting multiple items to wash was not suitable for working with items that are not worn/wielded/carried by the character (must've been fixed in DDA at some point)
2. activity handler for item washing activity was unable to work with items that are not worn/wielded/carried by the character (was fixed in DDA as a side effect of The pockets PR)
