### ISSUE TITLE
blackhawk cant fly

### ISSUE THREAD

**Issue by SoggyLemon** [cataclysmbnteam/Cataclysm-BN#1547]
### Describe the bug

Blackhawk helicopter cant fly, i dont know if other helis do this too.

### Steps To Reproduce

try to make blackhawk fly
game says "blackhawk is too heavy for its engines"

### Expected behavior

being able to fly

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Amazon; Model: KFSUWI; Release: 5.1.1; Incremental: 40.6.5.9_user_659662020; 
- Game Version: 1180f84 [32-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges]
]

**Comment by Proxiehunter** [comment]
Never tried to fly a helicopter. Don't think I've run across a functioning one. It's worth checking with you that the helicopter engine is fully functional not damaged or faulty?

What about the contents of the helicopter? Are you trying to transport heavy loot in it?

These are worth clarifying before people try to bugshoot what might be normal behavior. 

Also, I think it should display a different message in this case (if the game isn't currently set up to display a more accurate message it _should_ be so people don't keep reporting it as a bug) but does it have sufficient _fuel_ to take off? An empty chopper's not going anywhere but if that's the case it _should_ mention that in the error message instead of weighing too much.

**Comment by SoggyLemon** [comment]
> Never tried to fly a helicopter. Don't think I've run across a functioning one. It's worth checking with you that the helicopter engine is fully functional not damaged or faulty?
> 
> What about the contents of the helicopter? Are you trying to transport heavy loot in it?
> 
> These are worth clarifying before people try to bugshoot what might be normal behavior.
> 
> Also, I think it should display a different message in this case (if the game isn't currently set up to display a more accurate message it _should_ be so people don't keep reporting it as a bug) but does it have sufficient _fuel_ to take off? An empty chopper's not going anywhere but if that's the case it _should_ mention that in the error message instead of weighing too much.

yes, the choppers engine turns on and even allows me to choose the speed, but for some reason it doesn't let me fly up, i have sense the lost the world though so i cant really do any other tests.

**Comment by chaosvolt** [comment]
Did you hit `<` instead of trying to go forward?

**Comment by SoggyLemon** [comment]
> Did you hit `<` instead of trying to go forward?

yes, even then if I try going forward it says "the blackhawk lacks wheels to move" or something like that compared to when i try to fly which says "the black hawk is too heavy for its engines"

**Comment by chaosvolt** [comment]
Yeah, not able to reproduce this:
![image](https://user-images.githubusercontent.com/11582235/168926413-a138e513-7ca4-4fed-86fd-ae4d43a6b2b1.png)

If it was merely overloaded or your engine was damaged, it would fail silently on trying to ascend, which will be fixed by https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1538 Meanwhile it seems like the message on running out of fuel is different:
![image](https://user-images.githubusercontent.com/11582235/168926784-9667909d-b790-4f78-8329-3f43b4408421.png)

My guess is you're still trying to move on land, which an unmodified Blackhawk can't do since it lacks wheels.

**Comment by Coolthulhu** [comment]
Important question: world has z-levels on or off?

**Comment by SoggyLemon** [comment]
> Important question: world has z-levels on or off?

bruh i feel dumb, i think this might have been why.

**Comment by chaosvolt** [comment]
That is however an issue in that there's supposed to be a message that prints when you try that.
