### ISSUE TITLE
Unable to interact with pets after loading saved game.

### ISSUE THREAD

**Issue by AluminumAlman** [cataclysmbnteam/Cataclysm-BN#174]
# Describe the bug

Loading the game after taming an animal does not allow you to interact with it, while before the load you were able.

# Steps To Reproduce

1. Start a new game.
2. Spawn a tameable animal.
3. Tame the animal with food.
4. Attempt to examine the friendly animal: interaction menu appears.
5. Save the game.
6. Load the saved game.
7. Attempt to examine the friendly animal: the interaction menu does not appear.

# Expected behavior

Saving and loading the game should have no impact when attempting to interact with a pet.

# Versions and configuration

 - OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7 version
- Game Version: 53a609f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

- note #1: this bug was (probably) introduced by #131 and happens on release 691-Win64-Tiles and other Win64-Tiles releases past 691.

**Comment by Coolthulhu** [comment]
Thanks
The bug was caused by new `"removed"` field not being set to `false` on load.

**Comment by DrPariah** [comment]
[https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack/issues/46](url)

Commenting here because we've run into an issue with a mod that seems to duplicate this intake, or something similar to it. Secronom mod causes animals tamed by Cattle Fodder to not remain tamed.

STEPS TO REPRODUCE:

1. Create a new world, vanilla.
2. Debug spawn at least 2 Cattle Fodder and a Cow.
3. Tame Cow with Cattle Fodder.
4. Interact with Cow, then take one step away and attempt to interact again. This should bring up the interaction menu both times.
5. Create a new world using Secronom (and Lore Expansion to avoid missing info issues) from the BN Mod Pack.
6. Repeat Steps 2 & 3 above
7. Interact with Cow, then take a step away and attempt to interact again - this should result in the action simply (E)xamining the square the now-friendly Cow is in.
8. Use another Cattle Fodder on Cow, interaction menu available again.
9. If you repeat the step away and attempt to interact process, you should get the same result as above - the cow does not allow additional interactions.

The reason I'm asking about this here is that the fix associated with this was done via hard coding, and didn't touch the JSON records. Secronom, AFAIK, does not have any hard coding associated with it. It does not use "copy_from" on any of the animals involved. It does have "fleshed" versions of several wild animals, changing types and behaviors, but these are separate from the main animals and deleting them doesn't impact the issue referenced above. That is, deleting Flesh Cows doesn't make the regular Cows tameable without using one Cattle Fodder per interaction.

Any possible insight as to what might be reverting the change/fix for this issue? If it's based around the "removed" field, can JSON actually impact that? Note that this does NOT happen on vanilla Bright Nights, nor does it happen with other mods that add/extend/modify what animals are tameable - ONLY with Secronom.

Versions and configuration
OS: Windows
OS Version: Windows 10
Game Version: a40a4de [64-bit]
Graphics Version: Tiles
Game Language: English [en]
Mods loaded: [
Dark Days Ahead [dda]
Secronom
Secronom Lore Expansion
]

**Comment by DrPariah** [comment]
OK, safe to disregard this. Figured out what happened. The Secronom mod had an entry that overrode the 'pet' effect, which is normally permanent.
