### ISSUE TITLE
Burning mycus ground will burn off the road

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#1882]
### Describe the bug

As title says, when lighting mycus ground on fire, it will make road tiles disappear when the fire burns out and a dirt tile replaces it. Roads have a concrete layer under asphalt.

### Steps To Reproduce

1. Spawn a fungaloid close to the road.
2. Wait for the mycus ground to appear on the road.
3. Light it on fire.
4. Wait.

### Expected behavior

I would expect concrete tiles or road (pavement) to be still there when fire burns out.

### Screenshots

![image](https://user-images.githubusercontent.com/72284934/191517376-db4501e3-93f3-4e9b-be2c-7ba4fe708802.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 2937745 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    Lighter vehicle parts [lighter_vehicle_parts],
    no ups mp3 [no_UPS_mp3],
    MSX Fake Snow [UDP_BN_FAKE_SNOW]
]

**Comment by Proxiehunter** [comment]
I always assumed the mycus ate the road so when you burned off the mycus there was only dirt left. It drasticly weakens walls so I assumed this was WAI.

**Comment by leoCottret** [comment]
I think it's simply because the terrain doesn't save what was before, so nevermind what was before micus ground becomes micus ground.
IMO this seems hard to fix without implementing a system to save precedent terrain and could be easily explained as @Proxiehunter said

**Comment by leoCottret** [comment]
For reference, the code for fungus conversion is in `fungal_effects::spread_fungus_one_tile`
It checks several tags, including the FLAT one that a lot of terrain tiles have.
This will make it convert things like:
- metal floor
- resin floor
- pavement

But not gravel (because it lacks the FLAT flag)

I suggest a new system:

Add extra a check on str_min (minimal strength to destroy) to avoid mycus converting things like metal, asphalt etc.
It would still be able to convert dirt and the like (check on "DIGGABLE")
Sand, clay, wood (check on str_min) -> we may have to change some numbers but it would be for the best, no idea why a wooden floor is the same as a pavement.

An other idea would be to straigth up add a "FUNGUS_CONVERTIBLE" flag (or the opposit)

In either case I think the conversion system needs to be change, it doesn't make much sense right now.
