### ISSUE TITLE
migrate to `simdjson` JSON parsing library

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#1919]
### Is your feature request related to a problem? Please describe.

A lot of load times are used in loading JSON.

### Describe the solution you'd like

[simdjson](https://github.com/simdjson/simdjson) can read JSON in 3GB/s, which could speed up loading speed significantly.

### Additional context
speed comparisons:
![](https://github.com/simdjson/simdjson/raw/master/doc/rome.png)

**Comment by olanti-p** [comment]
This would be quite a large project.

All of our data loading code uses a mix of object-style access through `JsonObject` and stream-style access through `JsonIn`. `simdjson` seems to be providing both, but I can't find in its docs whether there is support for mixing them, so it may require rewriting all deserialization functions in the code to use object-based approach and `simdjson`'s API.

Moreover, it's rather lightweight and does not support some of the functionality we desire (namely, check for unvisited members), so there will be need for additional wrappers or hackery.

>A lot of load times are used in loading JSON.

Most of the time is spent on data finalization though.

Here's a Visual Studio benchmark done on version 0a952bbfe2bfaf1cefe4d28564359fad5f192a3d (with some slight unrelated changes):
![image](https://user-images.githubusercontent.com/60584843/192494604-ad919c4f-48bc-4faa-bf78-237cc4aa55ac.png)
JSON loading takes up only 11.33%, and all deferred JSON loading does not even come up to 1%, the rest is spent on stuff like copying around tileset sprites, checking blueprint requirements, mapgen weights and item blacklists
![image](https://user-images.githubusercontent.com/60584843/192495542-590c7517-756b-4848-b8bc-81095f92c6a0.png)

Granted, this is on a rather beefy rig (Windows 11, Ryzen 7 5800H, 3200 MHz RAM, SSD); on older machines (and on HDDs) this would take up more time.

Anyway, here's a list of some alternative or related solutions to consider:
1. Porting https://github.com/CleverRaven/Cataclysm-DDA/pull/50143. It lowers load times by up to 33% (not sure we could beat it with `simdjson`), and is a finished solution tested to work with the similar codebase.
2. Packing up data JSONs into a single zip archive, same for individual mods. It may be faster to load a single zip, unpack it in memory and parse it from there rather than individually load each of ~2k files, especially on Windows which is quiet slow when dealing with tons of small files, and especially on HDDs. This solution may be implemented together with `simdjson` or flexbuffers.
3. Fine-tuning our own parser. `JsonObject` in particular allocates a string for each member it finds, this may be replaced with a non-allocating `std::string_view` or some alternative C++14 implementation. Same for visited members check in objects. Another speedup may come from replacing `std::map` and `std::set` with vectors and doing a binary search through them - there's rarely more than 20 members in an object, this may turn out faster (needs testing first).

**Comment by scarf005** [comment]
solution 1 and 3 looks like a good alternative, thanks for great explanation!
