### ISSUE TITLE
Leashed dogs ignore the leash when they see enemy

### ISSUE THREAD

**Issue by olanti-p** [cataclysmbnteam/Cataclysm-BN#1997]
### Describe the bug

Leashed dogs ignore the leash when they see an enemy.

### Steps To Reproduce

1. Obtain a short rope and a friendly dog
2. Add the leash to the dog, start leading it
3. Spawn a zombie 20 tiles away
4. The dog runs away to attack

### Expected behavior

The dog stays on the leash

### Versions and configuration

Game version 6b7f879b

**Comment by leoCottret** [comment]
I agree that this is a bug, but this is the default behavior of DDA leashes.
Instead of blocking the movements of the animal in a radius around you, they make it follow you "in best conditions".
I think the leash should block the animals movements no matter where they want to go, especially with a dog, it's not as if your character had soapy hands or something.
I'll see if I can somehow fix this.
