### ISSUE TITLE
32-bit binaries aren't actually 32-bit

### ISSUE THREAD

**Issue by Muffindrake** [cataclysmbnteam/Cataclysm-BN#20]
Grab a 32-bit release and use file on it.

    cataclysmdda-cth-lin-curses32-233/cataclysm: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=33eea0cb28084df78dabbd1362bd8dfb960a26c0, stripped

**Comment by elricsfate** [comment]
Thanks for the report @Muffindrake . We will see about getting this solved ASAP. Expect a fix within the next week or two.

**Comment by Coolthulhu** [comment]
I wasn't able to get it to compile. Travis doesn't have 32 bit environments, `pkg-config` doesn't seem to like cross-compilation without some magic option I don't know about. Setting the environmental variable for `pkg-config` path didn't work.

For now I disabled linux32 builds altogether. I don't know how to set it up right. I'll probably try later, possibly on Ubuntu instead of that remote trial and error I've been doing so far.

**Comment by chaosvolt** [comment]
Hmm. I'm hoping this doesn't have anything to do with why last release didn't include a 32-bit version. ;~;

**Comment by chaosvolt** [comment]
Welp. I'll take that as a yes since the *next* build lacks a 32-bit version as well. This is unfortunate. I've got one 32-bit setup and one 64-bit.

**Comment by Coolthulhu** [comment]
The Windows 32bit build should get unborked soon, I'll try to set it up today.
Linux version will stay disabled for a while, unless someone really wants it up, since ironically, it is harder to get it to work than the cross-compiled Windows one.

**Comment by chaosvolt** [comment]
Ah, I see. Sorry about that. No rush, even having this updated today was a pleasant surprise. I'd been holding off on some changes in Arcana until after the patch was updated.

**Comment by rtizzy** [comment]
@Muffindrake Hey Muffin. Was this resolved with a Pull?

**Comment by chaosvolt** [comment]
Unlikely as the repo has not been updated since 2017.
