### ISSUE TITLE
Grid soldering iron unbuildable with handheld soldering iron

### ISSUE THREAD

**Issue by Davidththird** [cataclysmbnteam/Cataclysm-BN#2002]
### Describe the bug

grid soldering irons are unable to be built with a soldering iron even if you have a second one to build it with, the game thinks you are going to use the soldering iron with the battery which causes the crafting menu to list the soldering iron ingredient as brown as thus not allow you to built the grid soldering iron

### Steps To Reproduce

1. get all the materials and skills needed
2. try to construct it with a soldering iron
3. profit

### Expected behavior

grid soldering iron is able to be built

### Screenshots

![image](https://user-images.githubusercontent.com/59121922/194978548-7c820b7b-a8af-48c7-a2bb-ef6470f5373b.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 606d92c [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Magiclysm [magiclysm],
    No Lifting Reqs [disable_lifting],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by RelMayers** [comment]
Brown color indicates that soldering iron cannot be used as component and tool at same time.

**Comment by Proxiehunter** [comment]
> Brown color indicates that soldering iron cannot be used as component and tool at same time.

Yes, but my understanding is that should only apply when you're trying to use the _same_ tool as a component. If you have _one_ soldering iron and attempt to use it as the tool and the component as well then this should be happening and is not a bug. However the OP possesses _two_ soldering irons and this should not be happening. If that were supposed to happen then soldering iron shouldn't be a valid tool in the recipe because it could never be used.

Or did you mean that as a possible cause of the bug to investigate?

**Comment by RelMayers** [comment]
1 soldering iron of 1 with brown color
means its requiring additional soldering iron because currently you own only soldering iron which cannot do work on itself...

**Comment by Proxiehunter** [comment]
> 1 soldering iron of 1 with brown color means its requiring additional soldering iron because currently you own only soldering iron which cannot do work on itself...

But according to the original post this occurs while having _two_.

> grid soldering irons are unable to be built with a soldering iron **even if you have a second one to build it with**

Emphasis mine.

One thing I will suggest to OP now that I've had time to think on the situation is attempt it with both soldering irons having battery power and if that doesn't work attempt it a second time with the one you're using to build it having battery power and the one you want to use as a component with _no_ battery power and see if that makes a difference.

**Comment by joveeater** [comment]
I reproduced this and and tried it with both soldering irons having power. This caused the components required to change to a red "1 soldering iron".

**Comment by Davidththird** [comment]
> > 1 soldering iron of 1 with brown color means its requiring additional soldering iron because currently you own only soldering iron which cannot do work on itself...
> 
> But according to the original post this occurs while having _two_.
> 
> > grid soldering irons are unable to be built with a soldering iron **even if you have a second one to build it with**
> 
> Emphasis mine.
> 
> One thing I will suggest to OP now that I've had time to think on the situation is attempt it with both soldering irons having battery power and if that doesn't work attempt it a second time with the one you're using to build it having battery power and the one you want to use as a component with _no_ battery power and see if that makes a difference.

I actually did try all of this, if both have power neither can be used as a material.  
if neither have batteries, you don't have a tool of soldering to make the thing
order does not matter.

**Comment by Proxiehunter** [comment]
Then this is going to need someone to dig at the code to figure out what's gone wrong because this 1: should not be happening and 2: is reproducible according to joveeater. 

Sadly coding the game does not fall under my area of expertise. I assume however that whatever error is in the code is causing the game to attempt to use _all_ soldering irons as a component instead of using one as a component and one as a tool.

I'm going to boot up my copy and check something real quick.

**Comment by Proxiehunter** [comment]
Update's taking forever.

Okay, important data point. This is _not_ a universal issue when trying to use two of the same item, one as a component and one as a tool. A new character I just made _is_ able to make a stone hammer using one rock as a component and a second rock for the hammering tool.

And just to double check dropping one of the two rocks and moving away so I can't use the second causes the rock in the recipe to appear brown as it should when I only have the one.

This suggests the problem is likely in either the recipe or the soldering iron. This could however have something to do with battery power. I couldn't think of any non-soldering iron items that would be both a tool and a component that would be powered off the top of my head though.

I don't know what to look for in those but hopefully the extra data makes the problem easier to solve for someone who does know what to look for.

**Comment by chaosvolt** [comment]
See PR: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1528

**Comment by Krwak** [comment]
This bug is definitely valid and reproducible, just had a discussion about this in discord and it's still a problem to build this using handheld soldering iron.
