### ISSUE TITLE
`str` not extracted from `"name": {"str": A, "str_pl": B }`

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#2038]
### Describe the bug

`nearby fire` tool requirement is displayed as `없음`, which is `NONE`.

suspects:
- "str_pl": "none" is directly translated as "none" -> "없음"
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/5bdea27530148fa2674c5fd04e61052fb6c93953/data/json/items/generic.json#L16-L27
- object style name not extracted correctly? 

### Steps To Reproduce

1. change langauge to korean.
2. try to craft wooden spear. (나무창)
3. `nearby fire` is translated as `없음` (NONE)

#### gettext does not extract name in object form
![image](https://user-images.githubusercontent.com/54838975/196385155-1ecb09f1-12e9-4236-b277-e97aa381f355.png)
("nearby fire" is not extracted, only "str_pl")
[transifex link](https://www.transifex.com/bn-team/cataclysm-bright-nights/translate/#ko/lang-po-cataclysm-bn-pot--upload/301327229?q=text%3A'nearby+fire')

#### translation for `str_pl` printed out
![Cataclysm: Bright Nights - 5bdea275301_01](https://user-images.githubusercontent.com/54838975/196382178-1d541fb3-6b84-4708-955b-51bf450d0771.png)
![Cataclysm: Bright Nights - 5bdea275301_02](https://user-images.githubusercontent.com/54838975/196382194-3adbd1dc-40fe-43a3-84c1-cadab383b48d.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.1 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 5bdea275301 [64-bit]
- Graphics Version: Tiles
- Game Language: 한국어 [ko_KR]
- Mods loaded: [
    밝은 밤 [dda],
    NPC 욕구 제거 [no_npc_food],
    영양수치 단순화 [novitamins],
    고가 다리 [elevated_bridges]
]

**Comment by olanti-p** [comment]
This is not an extraction error, it's wrong use of plural form in JSON coupled with Transifex's UI choices and Korean apparently not having plural forms.

Running `lang/update.pot` extracts all strings from JSON into `lang/po/cataclysm-bn.pot` (which is then used as source for Transifex), and it can be seen that the resulting translation template matches the value in JSON:
![image](https://user-images.githubusercontent.com/60584843/196413746-1fc45f09-5984-4493-a903-3942db48cb64.png)

What is incorrect however, is how singular form is defined as `nearby fire` and the plural form is defined as `none`. That's not how gettext is supposed to work; `msgid` and `msgid_plural` in case of English source language should contain the same string used in singular (`n=0`) and plural (`n!=0`) contexts, or if the string is never used in plural form, simply not have a `msgid_plural`. We can't guarantee the latter due to how `nearby fire` is actually an item of which we can have multiple copies, so the next best thing is to use what uncountable items like `water` do and fill both `msgid` and `msgid_plural` with same value (in JSON, it's `"name": {"str_sp": A }`).

As Korean doesn't have plural forms, it's up to translators to choose which variant to translate, and in this case the singular form should have been translated.
![image](https://user-images.githubusercontent.com/60584843/196416302-913f7618-66a9-4100-960a-58e685055944.png)

Russian translation, where the issue is absent, for comparison
![image](https://user-images.githubusercontent.com/60584843/196416937-e18d61a4-ceb4-45e6-a095-d4a26f4512df.png)

Russian on Transifex, singular form (`msgid` -> `msgstr[0]`)
![image](https://user-images.githubusercontent.com/60584843/196417212-c7ac42c1-b5f6-40a4-a9c0-2e600192b51b.png)

Russian on Transifex, the 3rd plural form (`msgid_plural` -> `msgstr[3]`)
![image](https://user-images.githubusercontent.com/60584843/196417505-d4737648-4446-4633-a0fb-1fba5234f86f.png)

What I really don't get is why Transifex by default shows the plural form translation, it seems counterintuitive to me.

So what I think happened is, a translator selected the entry, saw `none`, didn't think to look at the singular form (from their point of view, it should also have been `none`, but in fact it was `nearby fire`) and translated it as `none`. 

The fix would be to change the JSONs to use `str_sp` and treat `nearby fire` (and similar items) as uncountable, which once merged will invalidate translations on Transifex, and translators would have to re-translate the strings, hopefully this time not falling prey to the UI.

**Comment by scarf005** [comment]
what's weird is that there's no `nearby fire` for translation at all. there's only entry for `none` in korean.
[transifex](https://www.transifex.com/bn-team/cataclysm-bright-nights/translate/#ko/lang-po-cataclysm-bn-pot--upload?q=text%3A'nearby+fire')
![image](https://user-images.githubusercontent.com/54838975/196421294-f5c06f4a-7741-4a5a-98e1-171811ce9978.png)

**Comment by scarf005** [comment]
continued in #2077 since underlying reason was something different
