### ISSUE TITLE
Zombies don't drop anything

### ISSUE THREAD

**Issue by shotgunfrenzy** [cataclysmbnteam/Cataclysm-BN#228]
# Describe the bug
Zombies don't drop anything at all when killing them

# Steps To Reproduce
1.Spawn in 
2. Kill a zombie
3. Notice it's just their body, nothing else

# Expected behavior
Zombies should have various loot due to their monster loot files, these seem to have stopped working since version 907

# Screenshots

https://i.imgur.com/IALOhlg.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 7aae68a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by DrPariah** [comment]
Can confirm, same thing happens to me, same parameters as above. Tried with pure 'vanilla' world, no item drops from zombies.

**Comment by Coolthulhu** [comment]
Thanks for the report.
I forgot one `!`. Logic changed from "are death drops empty?" to "are there no death drops?", but I forgot the "no", causing only monsters with no drops to drop things.
I pushed a fix, new version will have death drops again.

This is what happens when you only test your own changes and not playtest the game with them after that...
