### ISSUE TITLE
Crash when moving all items to floor using /

### ISSUE THREAD

**Issue by Kaylakaze** [cataclysmbnteam/Cataclysm-BN#229]
# Describe the bug

The game crashes when I push , from the / inventory screen to move all items to the floor, in some cases. I had this issue once before but couldn't repeat. This time, I've managed to repeat it consistently. Moving the items one at a time does not cause the crash.

# Steps To Reproduce

1. Load provided save game.
2. Press /. Make sure All 9 is selected on the left and one of the floor blocks is selected on the right
3. Press , on the All 9 (left) side.

# Expected behavior

All items should move to the floor for easy shredding

# Screenshots

N/A

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 7aae68a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Generic Guns [generic_guns],
    Graphical Overmap [Graphical_Overmap],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock [aftershock]
]

# Additional context
[config.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5572377/config.zip)
[Wichita Falls.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5572380/Wichita.Falls.zip)

**Comment by Coolthulhu** [comment]
Also in DDA: #41052

On our side, it was most likely introduced in #206
The problem is that `itemsPerPage` is not set when reopening the menu after move all, and it defaults to 0. If there are no items on a page, this results in a `0 % 0` operation in `advanced_inventory_pane::paginate`. `0 % 0` is undefined and causes the crash.

Normally, the `itemsPerPage` would be set by resize callback, but the `ui` (`ui_adaptor`) of advanced inventory is not set if `is_processing` is true. And it is true when the advanced inv menu is opened after finishing a move all action.
