### ISSUE TITLE
End goal of this fork?

### ISSUE THREAD

**Issue by John-Candlebury** [cataclysmbnteam/Cataclysm-BN#23]
As the issue asks, what is the end goal for this fork?

Is this just he github host for Coolthulhu Patches. Or is it supposed to eventually become a considerably different game, based on the idea behind the mainline Bright Nights mod?

I am asking because I am interested in contributing content to the Bright Nights mod, and want to know were to make PRs

**Comment by Coolthulhu** [comment]
If it's just content, it can go to CleverRaven - it will probably be more popular that way.
If it's NPC AI, fixing something that can't be fixed by simply altering the jsons, something strongly game design related (rebalance that actually ends up properly balancing things) - it goes here.

There is no set end goal yet. At the moment it is mostly just DDA with some of the wrong things fixed. So for now "less wrong DDA" could be considered the goal.

**Comment by John-Candlebury** [comment]
Thanks for the answer.
