### ISSUE TITLE
Some simple items such as webbing belt are VERY hard to repair

### ISSUE THREAD

**Issue by metalheimer** [cataclysmbnteam/Cataclysm-BN#2425]
### Describe the bug

There are some items that are very hard to repair for unknown reason. This is disregarding that webbing belt uses synthetic fabric as material (and steel). It's the steel repair that's hard. In fact, I as a longtime player still don't know what determines item repair difficulty. I've tried diving into the files several times in the past, to look into this, but never figured it out. There's nothing in JSONs to hint at item repair difficulty. Best I can figure it's about skills, char stats, and the amount of damage sustained, but there's something more than that. So I think this is a definite basic level issue. If the difficulty follows some formula, based on such as item volume and weight, could we have the results of that formula generated and printed somewhere, be it in item description or generated into the files? If item repair difficulty stat could be mass-inserted into the files for each item, then it also could be edited to make overrides for some items later.

To name another item, tactical dump pouch is also excessively hard to repair.

A slightly related issue is that the repair prompt doesn't mention which material it's about to use, and even worse, how MUCH it's going to use, and how much is nearby.

### Steps To Reproduce

Try repairing that webbing belt, why don't you. You webbing belt repair-attempting son of a bleep.

### Versions and configuration

Win 64bit

**Comment by Zireael07** [comment]
Those items are likely missing repairs_like field.

**Comment by chaosvolt** [comment]
In a nutshell: for most items, the difficulty to repair is puzzled out by the recipe for that item, if it exists. If it's uncraftable, an item can have `repairs_like` assigned to it to tell it that it should use the difficulty of another item, ideally one that is also craftable. If it lacks either of those things, the difficulty is basically maxed out.

So that means webbing belts and tactical dump pouches need a `repairs_like` entry. Any others that might've been overlooked?

**Comment by metalheimer** [comment]
>Any others that might've been overlooked?

Prob 5-10 other items I've come across but I can't remember which. Will have to keep an eye out.
