### ISSUE TITLE
Crash on loading DeadPeople tileset

### ISSUE THREAD

**Issue by Firestorm01X2** [cataclysmbnteam/Cataclysm-BN#245]
Got anonymous report.
Windows 7. X32. DirectX9.
Build: 972
Video card: Intel Graphics Media Accelerator (GMA) 3150 

Game crashing on loading DeadPeople TIleset
Ultica tileset does not produce any kind of errors.

![16067454939380](https://user-images.githubusercontent.com/17512620/100630676-e7348d00-333b-11eb-9bee-89b9397adbf5.jpg)
![16067454939391](https://user-images.githubusercontent.com/17512620/100630680-e8fe5080-333b-11eb-82a2-d6ced925f556.jpg)

he program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: bbd2a5d
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

  #0
    (dbghelp: @0x5a3448[cataclysm-tiles.exe+0x1a3448]), 
    (libbacktrace: _Z21debug_write_backtraceRSo+0xd9@0x5a3448),
    (libbacktrace: 0x5a3448    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x594c59[cataclysm-tiles.exe+0x194c59]), 
    (libbacktrace: log_crash+0x2d7@0x594c59),
    (libbacktrace: 0x594c59    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x594fbb[cataclysm-tiles.exe+0x194fbb]), 
    (libbacktrace: signal_handler+0x52@0x594fbb),
    (libbacktrace: 0x594fbb    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: raise+0x18c@0x75495e8f[msvcrt.dll+0x65e8f]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

**Comment by Firestorm01X2** [comment]
Personally I could not reproduce issue. But I am using Win10

**Comment by Wreckstation** [comment]
Ask them if they have their debug log. I had a similar crash that I reported on the [BN Updater](https://github.com/DoctorGoat/BN_Update/issues/7) which was caused because there were conflicting duplicate tilesets with the same id of DeadPeople from installing the DeadPeople set from both the original github and the packaged one from BN.

**Comment by olanti-p** [comment]
Apparently at least 2 people had this problem, and resolved it by switching to a different renderer.

The error looks to be the same as in CleverRaven#29568 (and possibly CleverRaven#41925), so it's most likely caused by some systems having low video memory / not supporting texture sizes / formats.

I don't think much can be done here besides swapping that `assert` with a `debugmsg` advising player to switch to a different renderer.
