### ISSUE TITLE
Add possibility for noise modifier for ammo (subsonic rounds)

### ISSUE THREAD

**Issue by metalheimer** [cataclysmbnteam/Cataclysm-BN#2498]
### Is your feature request related to a problem? Please describe.

I expected subsonic rounds to be more silent, especially with suppressor. But not only it turns out they are just as loud as any normal supersonic ammo, it's impossible to reduce their noise without modifying the source code. I did notice the suppressor has a noise modifier, and I tried applying it to subsonic ammo but it doesn't work (debug errors). So, if the suppressor can reduce noise, why not any other item?

Frankly, I'm clueless about the noise creation process. Guns don't have a noise stat in JSONs, neither does ammo, so...

### Describe the solution you'd like

Noise modifier for ammo. Unsure about what would be balanced as end result. Maybe 10-15 tile noise radius with ss ammo and suppressor.

**Comment by chaosvolt** [comment]
I could've sworn that was a feature in the past.

**Comment by Ignaramico** [comment]
IIRC the noise is made with the damage after certain threshold, so if gun damage + bullted damage >x you get the sound, unless you modify the ammo/gun "loudness"? (forgot the syntax)

**Comment by chaosvolt** [comment]
I do recall that guns, if not also ammo, can modify loudness. Or could, but I don't recall any instances of it being used much in current JSON, and don't know whether the feature might be defunct. It might now only be functional on gunmods.

**Comment by Dueu** [comment]
A way that guns can have reduced amount of noise made when shooting is with the "loudness_modifier" gun mod modifier, some guns have integrated suppressors with this modifier but not enough to suppress to near or completely silent beside a few rare instances when the bullet itself does little noise to begin with and can be suppressed with a external suppressor but those rounds are generally weak as they are of lower calibers like .22 LR.

I tested out what happens when you make a normal suppressor to have a loudness_modifier of -9999 and it completely removes sound. Unfortunally I think there is no way to actually make the rounds subsonic thus less noisy directly, you need a suppressor.

Also Scarf would like Feature Requests in dicussion rather than in Issues #2441 but you do you.

**Comment by chaosvolt** [comment]
So I'm guessing neither `loudness_modifier` nor `loudness` are valid in ammo?
