### ISSUE TITLE
Unable to start the game

### ISSUE THREAD

**Issue by Gozag** [cataclysmbnteam/Cataclysm-BN#254]
# Describe the bug 

I downloaded cataclysmbn-1027-win64-tiles.zip, and Unziped it. I executed cataclysm-tiles, but the game crashed even not showing the main screen. 

and an error massage appears.
an error massage is:

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 4b79191
TYPE: Signal
MESSAGE: SIGABRT: Abnormal

There is no config file in bn file. crash files too.
 

# Steps To Reproduce

Every time I execute cata-tiles it crashes and crashes and same error messages. I never played c-bn before.

# Expected behavior

I think there is only four files so those files are lack to start the game. 

# Screenshots

![301073OTP](https://user-images.githubusercontent.com/68036078/101441057-8caeb880-395b-11eb-9233-90ed09116888.png)

there is only four files. 
![003880OTP](https://user-images.githubusercontent.com/68036078/101441202-edd68c00-395b-11eb-9d08-9c375b45b804.png)

full error massage.
# Versions and configuration

VERSION: 4b79191
# Additional context

I tried to find error message files, but I have no config files, so there are no error files.

**Comment by Coolthulhu** [comment]
This was solved on discord.
Turns out the crash was happening because the game was located in "Program Files (x86)", which isn't writeable by the user. Moving the game to a directory where the user has write rights solved the problem.

We need to detect this case better. The game should print an appropriate error message in such a case.
