### ISSUE TITLE
Sticky Breaki iv segfault (AKA Get long sticc bugged lol)

### ISSUE THREAD

**Issue by tyrael93** [cataclysmbnteam/Cataclysm-BN#266]
# Describe the bug

Breaking a long stick on your person with the action menu "a" while standing on some long sticks triggers a crash. I've been able to reproduce it every time with the save I've included in this post. 

# Steps To Reproduce

Press "a" to activate the long stick in your inventory, break it. repeat the action. The prompt will tell you that you have a long stick on you even if you don't. Happens semi-randomly with the 2nd, 3rd, 4th or 5th long stick, usually the third, but has happened as far as the 7th try.

# Expected behavior

Not that.

# Yer Save
Here. 
https://files.catbox.moe/7hdnd5.zip

# Yer Mods
Alexa, print screenshot.
![Screenshot from 2020-12-17 10-08-37](https://user-images.githubusercontent.com/5557920/102466905-ec8a1b00-404f-11eb-9430-a72e8fa28ad0.png)

**Comment by Coolthulhu** [comment]
```
"use_action": "BREAK_STICK",
```

Hardcoded stick breaking functionality

```
if( p->get_str() < 5 ) {
        p->add_msg_if_player( _( "You are too weak to even try." ) );
```

Just

I wasn't able to reproduce the crash.
I can see why would it happen, though: the function first deletes the stick, then returns 1, which prompts the function below it to delete the stick that is being broken. If that stick no longer exists (because it was deleted a moment ago), the behavior is undefined.

I think I'll just purge the stick-breaking functionality and make it a deconstruction recipe.
The gameplay impact of denying little girl roleplayers the ability to break sticks is minuscule.

**Comment by tyrael93** [comment]
works for me
thanks
