### ISSUE TITLE
Hitpoints on walls

### ISSUE THREAD

**Issue by rafaelkb** [cataclysmbnteam/Cataclysm-BN#273]
**Is your feature request related to a problem? **

Yes, imagine this situation:

 You are in a lab underground.

 You have a pickaxe and there is a metal door in front of you with some tasty loot that you want to put your hands into.

 You equip your pickaxe and choose the option to strike the door with your pickaxe.

 The "health points" of the door starts from 100%, goes to 75%, then 54%, etc. Like it should be. Right? No problems until now.
 
 But then, a zombie scientist appears attracted to the sound of your pickaxe.

 The HP of the metal door was at 10% but you press 5 to stop destroyong the metal door and go kill the zombie scientist. The door was almost totally destroyed and this should be no problem.

After killing the zombie scientist you go back and press the option to destroy the metal door with your pickaxe again.

But wait. 

The HP of the door is at 100% again.

How could this be? Did the metal door traveled through time? Did the metal door regenerated like wolverine? No one knows. How do we fix this?

**Describe the solution you'd like
A clear and concise description of what you want to happen.**

 I say that we should have hitpoints on the walls and metal doors.

But this might be a problem because the cbn world have hundreds of thousands of blocks, so the information of the wall hitpoints would be huge. Unless..?

Instead of:

Store the data of the HP of all walls on the world:

 Wall 1 = 100% HP,
 Wall 2 = 100% HP,
 Wall 3 = 75% HP,

We only keep recorded the hitpoints of walls that are hit. That would be minimal.

Wall 1
Wall 2
Wall 3 = 75% HP,

**Additional context**

I don't think that this will be bad for Cataclysm Bright Nights. It's a great feature. And where's the bright nights subreddit and discord? I really want to help you all develop this.

We also would need to make a way to fix walls and metal doors btw.

**Comment by Coolthulhu** [comment]
At the moment, having terrain and furniture store data is rather difficult.
For example, incomplete constructions, computers, electric grid elements, all have their own special handling, even for things that could be shared.
If the case was strong enough, it wouldn't be a huge obstacle, though.

But I think that your specific use case - using a pickaxe - could be solved in a way that is easier to implement: by turning digging into a construction job.
Activating a pickaxe would just start this construction. Jackhammer would use the same construction, just do more work at a time.

The reason I'd prefer a construction over hp is because hp would add details which, in many cases, would be a bit troublesome:
* How to display damaged walls? Would they need extra sprites for different hp thresholds? What about ASCII display?
* How to repair them? This would require new jobs, specific handling and so on.
* How to handle constructing-over and deconstructing damaged objects?
* AI would have to understand damaged objects.
* The OCD factor of having damaged stuff everywhere. Would get worse if we finally got "base defense" gameplay aspect working.

If someone were to handle all that, I'd be fine with having it implemented as HP.
But if I were to implement it myself, I'd avoid the extra detail. At least until multiple use cases show that HP is the right way to do it.

> And where's the bright nights subreddit and discord?

There's no official discord yet, but we have channels on friendly discords:
https://discord.com/channels/699895400253095956/755928277226487868
https://discord.com/channels/598523535169945603/747868502953558127
https://discord.com/channels/716403896318296084/733601534436180079
Reddit: https://www.reddit.com/r/cataclysmbn/

> I really want to help you all develop this.

Would be very nice. Help is appreciated.

**Comment by Coolthulhu** [comment]
Closing as stale
