### ISSUE TITLE
Translated Japanese mod "Mizu" not fully compatible

### ISSUE THREAD

**Issue by NormieHere** [cataclysmbnteam/Cataclysm-BN#28]
Game version: cataclysmdda-cth-win-tiles64-269

Operating system:  Windows 10 Pro

Tiles or curses:  Tiles

Mods active: Mizu(meaning water); Boats; more_survival_tools.       (The same exact behavior seen here is also evident in the creators other mod 'Sabaku'(Desert themed instead) and 'Mori'(forest themed))

### Expected behavior 
Mapgen should have many more fields, some new sites, and fields should mostly be full of deep water, all to imitate major flooding. 
### Actual behavior
 The overmap generation changes correctly, rivers are slightly larger and there are fields everywhere. Also, the custom field templates seem to work as intended, being islands surrounded by water. In game play, fields are mostly unchanged, despite supposedly being the most evidently changed areas. They have the standard grass and dirt generations, with extremely sparse amounts of Deep Water tiles, which should cover the fields entirely. 
### Steps to reproduce the behavior
 Simply load a game world with Mizu as an active mod.

**Comment by Coolthulhu** [comment]
Any link for the mod?

**Comment by NormieHere** [comment]
I got them in a package of translated mods. I’ll send the relevant ones here. And thanks for the insanely fast response!

Sent from Mail for Windows 10

**Comment by Coolthulhu** [comment]
The problem was with the mod itself, it used old groundcover definition.
Here's a version with updated groundcover and updated braziers:
http://s000.tinyupload.com/index.php?file_id=59013613362915528837

The brazier change broke some mods, so if you want to use 269 build (which has old braziers and thus works with unupdated mods), just copy regional_settings.json from the file above, but keep the rest unchanged.
