### ISSUE TITLE
mess kits boiling doesnt work

### ISSUE THREAD

**Issue by Troll-Miki** [cataclysmbnteam/Cataclysm-BN#292]
# Describe the bug

Mess kits have boiling quality 2-3, but it doesnt work in craft menu

# Steps To Reproduce

1. Take mess kit
2. Try to craft clean water
3. Craft menu doesn't see the mess kit boiling quality

# Expected behavior

Craft clean water with only mess kit.

# Screenshots

![](https://i.imgur.com/fHulwRr.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: b2eece3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Coolthulhu** [comment]
I think I know why it happens:
Loaded items can't use their boiling quality. Just that specific one. This is because most of those items are containers in which you boil stuff, so you need them to be free to fill them with something to boil.

There are two ugly edge cases here:
* When your boiling item is filled with what you'd like to boil
* When your boiling item is loaded with batteries, which makes it filled

This is the second case.
I see following possible fixes:
* Remove boiling from mess kit
* Remove the requirement for boiling tools to be empty
* Add a special hack for mess kits to provide boiling quality when loaded

**Comment by Firestorm01X2** [comment]
I've definitely dealt with something like this before
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/76

**Comment by Coolthulhu** [comment]
Now that I'm reading the new logic, it also seems wrong:
If the item is loaded, it has contents. Meaning the second part of the check (the one for tools) only triggers for UNloaded items.

I must have tested it wrong. I probably spawned a container with boiling quality, like a glass bottle.

The correct logic would probably be
```
if( id == quality_id( "BOIL" ) && !contents.empty() &&
    ( !is_tool() || has_item_with( boil_filter ) ) ) {
```

Except for one caveat (at the bottom of my post).
This way: if it's empty, it's good to go. If it's not empty and it's not a tool (it's probably a container), it's out. If it's a tool, it gets an extra chance: if it's only contents are mods or batteries, it's still good.
Or, expressed more explicitly:
```
if( id == quality_id( "BOIL" ) ) {
  if( contents.empty() ) {
    // Nothing
  } else {
    if( is_tool() ) {
      if( has_item_with( NOT( boil_filter ) ) ) {
        return INT_MIN;
      }
    } else {
      return INT_MIN;
    }
  }
```

Note that `NOT` - we'll need to invert the filter, since we don't care about items that the filter likes, we only care if it find something it doesn't like.

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/46247

**Comment by Firestorm01X2** [comment]
@Coolthulhu maybe we actually should just allo to use boil items regardless of their contents, pretending that player just stores tool contents elsewhere during boiling?
