### ISSUE TITLE
Inspecting a weapon in the inventory menu crashes the game after applying a caliber conversion kit

### ISSUE THREAD

**Issue by Muffindrake** [cataclysmbnteam/Cataclysm-BN#303]
# Describe the bug

Game crashes when looking at a gun that just had its caliber converted to another.

# Steps To Reproduce

1. Acquire weapon that can have its caliber converted (tested Glock 17C and AR Pistol)
2. Apply caliber conversion kit to weapon (tested .45 on Glock 17C and .308 on AR Pistol)
3. Open inventory and look at the weapon in question
4. Observe immediate crash

# Expected behavior

Expected world peace and hugs. Also cake.

# Screenshots
XXX
# Versions and configuration

- OS: Gentoo Linux
- Game Version: b2eece326b
- Graphics Version: Terminal
- Ingame Language: English
- Mods loaded: dda, no_npc_food

# Additional context
[crash.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5758091/crash.log)
[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5758092/debug.log)

**Comment by Coolthulhu** [comment]
During testing this bug, I also discovered another: you can mod a weapon to use different ammo without unloading it.
You can't apply other kinds of mods to loaded weapons. It's probably inverted logic.

**Comment by Coolthulhu** [comment]
Alright, the bug happens because the gunmod doesn't set a magazine type for the gun and the gun lacks a default magazine for a given type.
It can't be solved easily, which was probably the reason most of the conversion mods were obsoleted.

For now, I'll just fix the crash and add a warning that a given mod+gun combo doesn't have a valid magazine for it.
