### ISSUE TITLE
NPCs Eventually enter InfiniteLoop

### ISSUE THREAD

**Issue by I2pRandom** [cataclysmbnteam/Cataclysm-BN#3036]
### Describe the bug

NPCs after a so many turns are entering a permanent infinite loop. 

### Steps To Reproduce

1): Spawn a handful of NPCs
2): Pass time and eventually the NPC will enter an infinite loop, and will re-enter the loop after waking them up.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/42506001/772ead5d-e48f-44e0-8377-eb708b9fb1d2)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/42506001/0359f72c-edb9-45a5-bf13-f1b396d69ca8)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/42506001/844d36af-2407-427c-ab0d-5cf81512070d)

### Versions and configuration

OS: Windows 10
Version: 402db5e
Language: English
Mods: [
  "bn",
  "Cata++",
  "aftershock",
  "gekkobots",
  "crt_expansion",
  "secronom",
  "secronom_lore_expansion",
  "Arcana",
  "magiclysm",
  "meguca",
  "Nechronica_Redux",
  "M.A.G.Armory",
  "underrailmetro_mod",
  "valchron_mod",
  "steampunk_arcanum",
  "Essence2200",
  "BL9_100monres",
  "elevated_bridges",
  "lones atomic additions",
  "Chorus Primitive",
  "Chorus Arcana Addon",
  "Chorus_Weapons",
  "Chorus CBMs",
  "Chorus_Starts",
  "cbm_slots",
  "lones_CBM_slot balance",
  "translocator_gates",
  "flesh raptors",
  "lonestweaks",
  "lones_UPS",
  "crazy_labs",
  "DracoDogMod",
  "DracoPigMod",
  "mutant_animals",
  "mutant_insects",
  "Youkai_Disco",
  "modular_turrets_no_blacklist",
  "Salvaged_Robots",
  "basement_extension",
  "oa_early_game_mutations_mod",
  "more_locations",
  "whaleys_tallbuild",
  "Ships",
  "trailerpark",
  "P_Caches",
  "morlock_village",
  "Animatronic_monsters",
  "randomized_mall",
  "water_towers",
  "Fewer_Farms",
  "more_survive_notes",
  "Survivors_Lost_item",
  "powder_disinfectant",
  "homemade_fungicide",
  "Bootleg_Walkers",
  "advtech",
  "makeshift",
  "anti_fungal_gears",
  "XEAS",
  "ProjectKawaii",
  "makeshift_stuff",
  "AAA",
  "ArmUpSurvEx",
  "More_Armors",
  "CIVILIANPOWAAA",
  "a_mutated_arsenal",
  "SD_Magcrafting",
  "Arts' Guns",
  "arsenal_breach",
  "fallout",
  "fallout_jm_npc",
  "modern_weapon",
  "ExArch",
  "pressure_weapon",
  "Cannala",
  "porawep",
  "pneumo_fun",
  "VermilionMod",
  "adv_gear",
  "ETC_handguns_etc",
  "SM",
  "bioco",
  "Bionic_Space_Expander",
  "bio_recipes",
  "CBM_Arms",
  "Medieval_Mod_Reborn",
  "homestead",
  "private_defense",
  "culinary_days_ahead",
  "Gourmand'sGraces",
  "CerealMod",
  "Tolerate_This",
  "dried_fruits",
  "growable-pots",
  "Uekibati_mod",
  "WildLiving",
  "CasingCrafting",
  "Pix's Shit",
  "incinerator",
  "no_UPS_mp3",
  "Arcana_aftershock_Patch",
  "Arcana_Magiclysm_Patch",
  "Arcana_Crit_Patch",
  "Arcana_Cata++_Patch",
  "more_survivor_stuff",
  "jury_rigged_robots",
  "MMA",
  "MMA_Mods_Extension",
  "sarcophagi_access",
  "ks_variety_pack",
  "even_more_mutations",
  "mutant_npcs",
  "hydroponics",
  "Mining_Mod",
  "recruitment_options",
  "Thogs_Vehicles",
  "Thogs_Things",
  "wandering_masters",
  "Merchant",
  "Tankmod_Revived",
  "Heavy miners",
  "blazemod",
  "vorpal_weapons",
  "deoxymod",
  "magicrevamp",
  "demon_spider_a",
  "vamp_stuff",
  "vamp_stuff+arcana",
  "necromancy",
  "amplified_players_features",
  "no_npc_food",
  "novitamins",
  "bow_opness",
  "shinigamimod",
  "Mutation_Changes1",
  "blaze_extension_M",
  "sci_turret"
]

### Additional context

[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/12185458/debug.log)

**Comment by chaosvolt** [comment]
So I'm looking into this a bit, in the specific case of Cata++ NPCs I've noticed this seems to happen nearly every time when you START at the location they spawn in via the experimental soldier start, but don't seem to bug out immediately if you start in other locations and visit them.

I've yet to encounter any infinite loops with static NPCs in vanilla but fairly certain I saw at least one with a dynamic NPC.

I'm not sure yet what the cause is, but messing about with testing now.

**Comment by chaosvolt** [comment]
I've made some progress in testing:
1. It can be very easily tested by starting at the makeshift command center via the "experimental solder start" scenario, as this gives you four different NPCs who are prone to doing this right after you spawn in.
2. The two super soldier NPCs do this nearly every time you test this. Removing `bio_blade` from their NPC class bionics seems to make this stop happening.
3. The two bio-weapons seem to do this far less often, but still sometimes do. If the same cause is responsible, it's most likely because `bio_tools` also comes with the extended toolset, which counts as a bionic melee weapon (albeit one not intended as weapon, presumably the reason why it happens way less often).
