### ISSUE TITLE
Can't heat up MRE with heat pack

### ISSUE THREAD

**Issue by butnugit** [cataclysmbnteam/Cataclysm-BN#32]
Game version:397

Operating system:win10

Tiles or curses:tiles

Mods active:none

### Expected behavior
use heat pack from mre to heat it up and get morale boost
### Actual behavior
heat pack doesnt appear in use window. going to inventory, selecting heat pack and activate produces message "you can't do anything interesting with the heat pack"

**Comment by Coolthulhu** [comment]
I disabled the food heat mechanics because they required a rather large system for a minor gain. Making a good use of food heating also required manually (ie. as the player, not the character) applying the heating.

Unless someone has a good idea on how to make a non-tedious, meaningful food heat system, I will probably not be bringing it back.
Alternatively, I'll bring it back if a lot of people want it or someone writes it for me.

Still, for now the heat packs are useless, so I should either stop them from spawning or at least make their description clear.

**Comment by butnugit** [comment]
Ah, I see. My bad, then.
