### ISSUE TITLE
external tileset sprites for basic armor items

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#3231]
> At some point remind me to also add external tileset sprites for them so they don't use the derpy-looking ballistic mask overlay. Probably will glom onto the mask of insight sprites from Arcana as a base.

_Originally posted by @chaosvolt in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3221#issuecomment-1732445902_

```[tasklist]
### Missing external tileset
- [x] arming cap
- [ ] iron battle mask
- [ ] bronze battle mask
- [x] iron armguard
- [ ] bronze armguard
```

**Comment by chaosvolt** [comment]
Hecc. I assume or would hope that iron armguard already has a sprite since it's a pre-existing item. Arming cap can probably coast on looks-like making it resemble the helmet liner, so that only really leaves the masks (since ballistic mask looks silly) and probably proper bronze-looking sprites for the bronze arm guards.
