### ISSUE TITLE
Is there a mod for DDA to make it BN?

### ISSUE THREAD

**Issue by PGR-14** [cataclysmbnteam/Cataclysm-BN#3272]
### Is your feature request related to a problem? Please describe.

How do you get Bright nights as a mod for Dark Days Ahead? Cause some mods I want to try out needs BN as a dependency.
Is there any way to get it as a mod, I've seen the game part, but there isn't a mod version

### Describe the solution you'd like

A mod?

**Comment by olanti-p** [comment]
Unfortunately that's impossible.

The whole reason why BN is a fork (a different game) instead of being a mod for DDA, is because the amount and nature of changes we want are far beyond any abilities of DDA modding system.

It may be possible that the mod you want comes in 2 variations: for BN and for DDA, but you'll have to refer to the mod repository for that information (some mods clearly state they're a BN adaptation of DDA mod, or DDA adaptation of BN mod), or ask the author directly.

**Comment by chaosvolt** [comment]
All of my mods, and mods I'm involved in maintaining, currently have both a DDA and BN version so there's that at least.

That said, last I checked DDA fucked over basically every third-party mod with their charges removal changes and I hadn't yet worked up the time and energy to update the DDA versions of my mods due to being busy with IRL stuff a lot.

**Comment by PGR-14** [comment]
Well Cata++ needs it, and so does the Arcana patchmods

**Comment by chaosvolt** [comment]
I'll work on them eventually but been busy, yeah. @.@
