### ISSUE TITLE
NPC clothing is clean after murder

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#3429]
### Describe the bug

NPC's are a great source of clean clothing, when you kill them it doesn't make their clothes filthy.

### Steps To Reproduce

1. Keep filthy clothing enabled
2. Kill an npc.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/7affc574-20ba-4860-b4e8-5f1162534dd0)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/78afb256-5c33-4036-8630-b0b4e3b6c58e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 61c1386 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 [Essence2200],
    Essence 2200 Tweaks [FoxTweaks],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Urban Development [Urban_Development],
    Cataclysm++ [Cata++],
    C.R.I.T. Expansion [crt_expansion],
    Battle Maid Redux [battle_maid]
]

### Additional context

It ain't much, but it's honest work.

**Comment by chaosvolt** [comment]
They aren't gnarly festering animated corpses so uh, this seems working as intended. We don't really have bloodstained clothing as a feature and we'd need DDA to implement NPCs shitting themselves when the die so we can port that (a nessecary addition to the inevitable need to track all bodily functions eventually, surely) so there's not really any logical reason an NPC dying should make clothing any more filthy than the ones that spawn on already dead non-zombie human corpses.

I guess that does leave the question of why a corpse rotting over time doesn't automatically filth up any clothing not yet moved from its origin tile over time if left undisturbed, but the obvious answers to that are:
1. It's definitely the sort of pointless faffing about for muh realisms that has no meaningful value in BN.
2. Every method to actually implement that will either require CBT to code in contamination of items over time, or just drunkenly hack it in by having ambient corpses spawn with pre-flagged filthy clothes. I don't know if the latter is a smart idea because we want it to not break No Filthy Clothing setting, and I have zero idea if NFC correctly turns ALL potential occurrences of the filthy flag off, or if it only disables the function of the filthy monsterflag generating filthy clothing on mondeath.

**Comment by RoyalFox2140** [comment]
It's just a very consistent source of good clothing/armor depending on the one you kill, making psychopath that much stronger. Killing a zombie in swat armor provides heavily damaged and filthy kevlar while an npc will provide it likely in decent condition and perfectly clean.

I didn't include the rotting corpses in the world to spawn with filthy clothing because that's a separate situation entirely.

**Comment by chaosvolt** [comment]
Eh, problems with that:
1. Houses have plenty of clothing spawns as it is, failing that it's not that hard to make the basics yourself even if you've committed to the suffering of grinding tailoring from zero.
2. Dressers full of clothing and the above-mentioned dead bodies also don't fight back, unlike NPCs who generally fight back better than most zeds.
3. The real balancing feature here is random clothing damage, not filthiness. That's been my number one complaint with filthy clothing since day one, it adds an extremely trivial step between you and your clothing that can even be ignored for the most part unless your have the Squeamish trait. A tiny morale penalty and an even tinier chance of taking blue wounds more often is barely a consequence compared to the risk of your precious new armor being sent into a damage spiral you don't have the skills to reverse, and/or having it torn right off of you and deleted from reality.

So in that regard, as far as murdering NPCs goes, their clothing takes damage from hits just as yours does. This does mean that it's pretty RNG-based whether you'll tarnish the reward a bit, but...

**Comment by RoyalFox2140** [comment]
I may as well just disable the mechanic on my side if people don't want to make it apply consistently. I play on 30-50% loot so finding a great source of clean armor outside of dangerous areas negates the mechanic without need for cleaning or crafting.
