### ISSUE TITLE
State of project

### ISSUE THREAD

**Issue by IriaSomobu** [cataclysmbnteam/Cataclysm-BN#35]
Hi! I have several questions about this fork:
- as stated in [this doc](https://github.com/cataclysmbnteam/Cataclysm-BN/wiki/Changes-so-far) this project took its own, independent way of developement. Does this means that you will never pull/push anything from upstream repo?
- can you describe goals of this project? What you are trying to achive?
- do you need help? If so, what kind of help you needed?

**Comment by Coolthulhu** [comment]
> Does this means that you will never pull/push anything from upstream repo?

Not necessarily never, but it's not going to be a regular thing. Mostly bug fixes for bugs common in both repos.

> can you describe goals of this project? What you are trying to achive?

A Cataclysm that is a game rather than a simulator.
Making the game more goal-oriented, faster, balanced, "fun".
Less about manually executing trivial actions (cooking food, washing clothing, repacking inventory), waiting for actions to complete, kiting trivial monsters, picking up ammo after fights.

> do you need help? If so, what kind of help you needed?

Help would be very appreciated.
I should probably make a page on wiki for this list.

* Reporting bugs. Including ones inherited from DDA.
* Identifying problems that aren't bugs. Misleading descriptions, values that are clearly off compared to similar cases, grammar mistakes, UI wonkiness that has an obvious solution.
* Making useless things useful or putting them on a blacklist. Adding deconstruction recipes for things that should have them but don't, replacing completely redundant items with their generic versions (say, "tiny marked bottle" with just "tiny bottle") in spawn lists.
* Tileset work. I'm occasionally adding new objects, like the new electric grid elements, and they could use new tiles.
* Balance analysis. Those should be rather in depth or "obviously correct". Obviously correct would be things like: "weapon x has strictly better stats than y, but y requires rarer components and has otherwise identical requirements".
* Identifying performance bottlenecks with a profiler.
* Code quality help.

PRs preferred where applicable, but a good report is also worth a lot.

**Comment by iillyyaa2033** [comment]
@Coolthulhu and a few questions more:
1. Translations
- is translations welcome?
- if so, is it worth to play with diffs of .po files on upstream and this repo instead of re-translating missing text?
- will you update [TRANSLATING.MD](https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/doc/TRANSLATING.md) and create own transifex account? Not right now but mabe somewhere in future?

2. Repo
- I think it is good idea to update at least README.md on project's root: remove DDA-related badges and info, add explanation of project goals similar to one you've written above;
- also I think is fine to update in-game title motd and credits too;
- am I wrong?

3. Other
- I cannot find android executable (.apk) file in releases. Are you experiencing problems with this build target?

**Comment by Coolthulhu** [comment]
> Translations

Yes, translations are good.
I don't know the quality of the .po files, so I can't really say.
In plans. I'm not focused on it because I haven't heard of anyone wanting to provide translations, but if there are people who would like to do it but can't, I'll start it ASAP.

> Repo

Yes, I just delayed it because I wanted content first.

> Other

I haven't gotten to it yet, though I started trying to get to it literally yesterday. Travis CI - the service I use for builds - has some quirks when it comes to android builds. It may not be a problem, but it may be a bit more complex than just setting build target to android. And the build script inherited from DDA is different for android and PC OSes.

**Comment by iillyyaa2033** [comment]
@Coolthulhu may I ask you to create BN translation project on transifex?

**Comment by Coolthulhu** [comment]
@iillyyaa2033 Alright, I finally got to it: https://www.transifex.com/bn-team/cataclysm-bright-nights
It's not working yet because I'm not sure how to hook it up to the repo. I'll look around and try asking DDA devs for help.

**Comment by Coolthulhu** [comment]
I think I set it up and managed to port old russian and polish translations. What's next?

**Comment by Firestorm01X2** [comment]
> I think I set it up and managed to port old russian and polish translations. What's next?

Could you add me to the translation team? Request was sent.

**Comment by MrOlaf** [comment]
"Make Cataclysm Fun Again" Seriously... Cataclysm DDA has been failing David Brevik's "mom test". I'm really glad CataclysmBN popped up and hopefully the fork will go towards the player having a choice of being an average joe traveling the world of the cataclysm in an armor plated truck or a mutation infused superhero with mouth-tentacles or a super villain stuffed full of cybernetics. Good luck Coolthulhu!

**Comment by Coolthulhu** [comment]
I think the questions in the thread have been answered. Closing as solved.
