### ISSUE TITLE
Primitive option for a ramp construction

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#3532]
### Is your feature request related to a problem? Please describe.

One cannot pull 1/2-tile vehicles up and down stairs.

### Describe the solution you'd like

It would be neat to have some sort of temporary ramp either as item available to deploy and use.

The alternative would be a primitive option for ramp construction, like wooden ramps out of planks, nails, rope or pipes+sheet metal ramps. Currently there's a concrete ramp construction option, which requires "advanced" materials.

**Comment by chaosvolt** [comment]
Wood or earth would be most fitting. Maybe even both. :>

**Comment by chaosvolt** [comment]
Added musing for anyone else while I'm at it: one problem with this is that ramp building uses hardcoded chicanery to be able to place the upper ramp surfaces. This means that adding more ramp options would require:
1. Hardcoding two new ramp functions per ramp material added, solely for the sake of generating the right type of ramp.
2. Reworking the existing ramp placement functions to basically do the above for us, placing different terrain depending on some if/else fuckery checking what kinda ramp we're building via its `post_terrain`.
3. JSONizing z-level `post_special` functions so we can magic up whatever terrain, up or down, we bloody well feel like.
4. Ignoring all of these pain in the ass conundrums by just removing references to the generic ramps being made solely out of concrete so that the same constructions, concrete, rammed earth, or wood, all create the same terrain in the end. Generic ramps are currently indestructible so we lose nothing unless we want the wooden ones specifically to be flammable, or if we decide we no longer want invulnerable ramps.

One added complication though: the feature is presently mod-locked behind the bridges mod. I feel like we'd much rather have these be in vanilla if we actually want to flesh out and expand on things, especially if we're gonna be adding even more hardcode functions that would otherwise be used solely by a glorified external option mod. See https://github.com/cataclysmbnteam/Cataclysm-BN/discussions/3533 for what we'd need to make this a non-issue.

**Comment by Unrepentant-Atheist** [comment]
Anything but hardcoding it.

**Comment by RoyalFox2140** [comment]
Wooden and earthen ramps added in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3919 by @chaosvolt Closable unless it needs more work.
