### ISSUE TITLE
Re-implement 3+ engines for vehicles

### ISSUE THREAD

**Issue by olanti-p** [cataclysmbnteam/Cataclysm-BN#389]
# Is your feature request related to a problem? Please describe.
A while back I've pulled in a commit from DDA that limits player's ability to install engines to 2 per vehicle: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/315/commits/bc6f0263700480a90374581ac4a38068cc202aae

3rd engine used to require 12 mechanics, but there are no crafting recipes in vanilla BN that allow to level it above 11. From my own memories, the skill didn't seem to grow past that number when doing constructions/repairs either, so I assumed getting 12 is impossible.

Apparently some people playing vanilla 0.E managed to gain level 12 by repairing/disassembling huge amount of cars (e.g. on longer sessions), and some mods like Aftershock introduce crafting recipes that allow leveling mechanics past 11.

That kinda turns that interface bugfix into an unnecessary gameplay restriction.

# Describe the solution you'd like
Some ideas:
1. Revert that commit. I don't _like_ this solution since it would leave 3rd engine a semi-false promise on vanilla, or force skill grinding.
2. Make it a game option, and allow mods to enable it. Seems suboptimal.
3. Revert commit, but drop required mechanics level to 11
4. Add a vehicle part that unlocks ability to install 3rd, or even 4th, engine (some kind of high-tech transfer case with load balancing; spawns in labs / some other appropriate high-level location)
5. Leave is as is. Having limited slots means more need for high-level engines (but then again, superdeathmobiles probably already have them)

**Comment by anothersimulacrum** [comment]
As it is, it will be more better to use a stronger engine instead of adding more - I am thinking that one of the major factors behind people wanting more engines is that the electric engines in game aren't very powerful  (even at the high end), and the powerful ones are quite rare. 
If you have a gas-fueled death mobile, you've got strong options, but not really for an electric one - the weak(er) engines will necessarily limit you.

**Comment by Proxiehunter** [comment]
A long time ago on the Cataclysm Discourse I had an idea about a recipe to cobble multiple engines into a combined engine item that would be stronger than either engine on their own (but probably slightly weaker than the sum total of the involved engines because of the jury rigged nature of the engine). But I didn't understand the entries for the engines well enough to try and actually implement it as a mod. That's a possibility to allow more engine power with technically only two engines since the game will define the frankenengine as one extra powerful engine for purposes of installation.

On the other hand allowing three or more engines not only helps push big deathmobiles it would allow me to add a gas, diesel, _and_ electric engine to a more normal sized vehicle and never have to worry that I'm not finding the right kind of fuel and my battery is draining too fast on the electrical engine.

**Comment by Lorith** [comment]
From what I recall, multiple engines had negative impacts as it was -- I had eventually hit a point where installing V6 engines reduced the speed rather than increased it, and later the same occurred with V8 and V12 engines.  I'd like to have multiple engines allowed due to differing playstyles being a thing.  Having something that can use all forms of fuel is nice, as is being able to lug ultra-heavy vehicles at high fuel cost.

Limiting engines based on total output would not be a good idea IMO, as it would restrict modding if someone wanted to make something like a cargo ship engine and slap it onto a land-train, I'd think.

Perhaps it could also be done a different way where you can attach an engine to a specific wheel, or to the drivetrain, which would limit to 1-2 active engines, while attached directly to wheel would allow as many as could fit?

**Comment by chaosvolt** [comment]
Question: can you still install 3+ engines if the parts involved lack the `E_HIGHER_SKILL` flag, or does this new hardcoded restriction interfere with that too?
