### ISSUE TITLE
Vehicle engine sound issue

### ISSUE THREAD

**Issue by Shackram** [cataclysmbnteam/Cataclysm-BN#410]
Hello, it's me again with a new soundpack related problem.

I kinda lost interest on cata for a few months, but last week i saw that the issue i had opened got fixed so i decided to give a shot and found a new small problem.

# Describe the bug

Using @'s soundpack or Otopack, when you start driving a vehicle the engine sound makes a very high pitched screech, but only when the vehicle is moving. If the vehicle is stopped but the engine running, it sounds fine, only when the vehicle starts moving it gets weird.

I imagine it's another SDL issue and might affect other looping sounds, but so far i only noticed it with car engines.

# Steps To Reproduce

1 - Drive a vehicle with an engine
2 - High pitched noise starts

# Expected behavior

1 - Drive a vehicle with an engine
2 - Normal engine noise

# Screenshots

[Video showing the problem](https://streamable.com/gukevr)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 09fab01 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Mythical Martial Arts [MMA],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills]

# Additional context

Right now i'm dealing with it by reducing the volume of the internal engine sound to 0 on the vehicles.json of the soundpack.
 
    "type": "sound_effect",
    "id": "engine_working_internal",
    "variant": "engine_vtwin",
    "volume": 0,
    "files": [ "vehicle/engine/engine_working_vtwin.ogg" ]

[I also saw another user with a similar problem on the CDDA sub](https://www.reddit.com/r/cataclysmdda/comments/lu5s8x/vehicle_engine_screeching/), so i went to see if i could reproduce the problem on the latest CDDA experimental, but instead... it crashes to desktop when i take the first step with a sound pack active.

**Comment by Coolthulhu** [comment]
I'm reading the sound code and it's pretty complex.
It has a lot of helpful debug output, though. To get it, you need to enable the debug mode. You can either bind it to a key and use that or manually activate/deactivate it by going enter->debug menu->debug mode.

Once debug menu is on, it should print some info every time a vehicle sound plays.

It may just be SDL, but it may be weird data fed to it. If it's the latter, it'll be easier to fix.

**Comment by CV514** [comment]
It seems that this may be related to how engine sounds in Otopack are made.
My possible solution was to try and create my own sounds with files from freesound.org, and from my experience this helps?

Here they are. I've changed electric and V8, didn't touched regular combustion. You can hear that the "original" combustion has some noticeable high pitch by itself even on idle which may transform into unpleasant pitch harmonics while driving.
https://drive.google.com/open?id=13Fjs13QOahsbZ47giMyVMn9AxF-3_GBO

Debug mentioned above is not very useful - it's only declares about sound start and stop, and pitch changes that related to the current speed. Even with that, I can't see how it can be extracted into readable text without sharing screenshots since info is written to combat log and not into debug.log (is there any launch parameter?)

If that helps, let me know, I'll take my time to work with other engine sounds as well. It may not be the ultimate solution since in my case this issue is less noticeable in the first place; depends on the sound output hardware, perhaps? I'm outputting PC sound through USB audio interface (KA6).

**Comment by olanti-p** [comment]
May be same as https://github.com/CleverRaven/Cataclysm-DDA/issues/48192.
Proposed workaround is to switch sound from 5.1 to 2/2.1 in Windows sound settings.
