### ISSUE TITLE
Multicooker not working

### ISSUE THREAD

**Issue by Lamandus** [cataclysmbnteam/Cataclysm-BN#4467]
### Describe the bug

When using a multicooker it will produce a "debug", the food is not produced.

### Steps To Reproduce

1. Have a multi cooker (with enough charges, that is another problem, but let's keep it away)
2. cook anything, wait for finish
3. error message comes up.
4. Debug is spawned.

### Screenshots

![grafik](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/7045bad0-46a7-4ed4-82f9-6fc9fced4dbd)
![grafik](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/56ac1f86-eba2-432c-a57e-e1751d27a91a)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: 9867e87 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Prevent Zombie Revivication [no_reviving_zombies],
    Lootzones [Lootzone],
    No Filthy Clothing [no_filthy_clothing],
    Limit Fungal Growth [limit_fungal_growth]
]

### Additional context

```
 DEBUG    : invalid recipe id ""

 FUNCTION : const T& string_id<T>::obj() const [with T = recipe]
 FILE     : src/recipe_dictionary.cpp
 LINE     : 65
 VERSION  : BN 9867e87
```

**Comment by Rosencratz** [comment]
Hello, I'd like to add to this issue. 
I have received a similar issue with multicooker outputting debug on 0.6 stable. 
Currently, I'm on the most recent experimental version by the time of this post. 
It seems that the multi-cooker just disappears from inventory once its cooking cycle is complete

Steps that I took to result in disappearing:
I tinkered a multi-cooker. 
I plugged in a medium high capacity battery
Then I ordered it to produce cooked meat 
I started driving slowly through a town
Halfway through I get a notification to "Stop cooking"
I pressed escape since I wanted it to finish cooking 
Then I checked my inventory and every space/storage within 1 tile of my space. 
Nothing! It's gone!

OS: Windows
Game Version: ab60661
Graphics Version: Tiles
Game Language: English [en_US]
Mods loaded: [
 "bn",
  "no_npc_food",
  "novitamins",
  "No_Rail_Stations",
  "no_reviving_zombies",
  "limit_fungal_growth",
  "BL9_100monres",
  "realdarkskies",
  "Cata++",
  "crt_expansion",
  "lones atomic additions",
  "translocator_gates",
  "aftershock",
  "lonestweaks",
  "lones_UPS",
  "Jake's_Squirrel_mod",
  "GOV_BANDITS_KAI_R",
  "gekkobots",
  "MagicalNights",
  "PK_REBALANCE",
  "pride_flags",
  "teleportation_tech",
  "WildLiving",
  "AbrahmsRecipes1",
  "adv_gear",
  "advtech",
  "anti_fungal_gears",
  "ArmUpSurvEx",
  "Tolerate_This",
  "bioco",
  "Bionic_Space_Expander",
  "bio_recipes",
  "expansion_tefnut",
  "CBM_Arms",
  "CIVILIANPOWAAA",
  "SD_Magcrafting",
  "craftgp",
  "culinary_days_ahead",
  "ExArch",
  "Gourmand'sGraces",
  "growable-pots",
  "Uekibati_mod",
  "homemade_fungicide",
  "jackledead_armory",
  "Make_a_Lot_of_Items_Mod",
  "metal_elemental",
  "More_Armors",
  "makeshift_stuff",
  "pneumo_fun",
  "Soy mod",
  "Survivors_Lost_item",
  "surv_crowbar",
  "thermal_ups",
  "blazemod",
  "vorpal_weapons",
  "Bug's life",
  "mutant_animals",
  "mutant_insects",
  "ks_variety_pack",
  "hydroponics",
  "jury_rigged_robots",
  "Merchant",
  "Mining_Mod",
  "more_survivor_stuff",
  "mutant_npcs",
  "MMA",
  "WIELD_WILD_WEAPONS",
  "P_Caches",
  "more_locations",
  "morlock_village",
  "deoxymod",
  "Tankmod_Revived",
  "Heavy miners",
  "shrub_mod",
  "amplified_players_features",
  "UDP_BN_FAKE_SNOW",
  "stamina_regen_buff",
  "fuji_mpp",
  "Mutation_Changes1",
  "necro_find",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills",
  "bow_opness",
  "tamebugs",
  "TaMu"
