### ISSUE TITLE
invalid monster flag: "CAN_BE_ORDERED"

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#4487]
```
 DEBUG    : Error: Json error: data/json/monsters/drones.json:18:100: invalid monster flag: "CAN_BE_ORDERED"

e": "collection", "groups": [ [ "robots", 80 ] ], "//": "80% chance of an item from group robots" },
    "death_function": [ "BROKEN_AMMO" ],
    "flags": [ "SEES", "FLIES", "NOHEAD", "ELECTRONIC", "NO_BREATHE", "INTERIOR_AMMO", "BIOPROOF", "
                                                                                                   ^
                                                                                                    CAN_BE_ORDERED" ]
  },
  {


 FUNCTION : bool main_menu::load_character_tab(const std::string &)
 FILE     : /home/scarf/repo/cata/Cataclysm/src/main_menu.cpp
 LINE     : 1020
 VERSION  : BN HEAD-HASH
```

prevents the game from loading. happens on all saves. not sure why invalid flags prevent the game from loading at all.

**Comment by chaosvolt** [comment]
Uh, what? That's from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4247

The flag should be 100% valid, it was tested by both of us.

**Comment by scarf005** [comment]
hecc, for some reason can't reproduce after recompilation.

**Comment by chaosvolt** [comment]
Just downloaded build `2024-04-14`, started a world, spawned a manhack, saved, then loaded. Couldn't reproduce it.

Probably came from loading an exe compiled from an old branch predating the PR being merged (since monster flags are all defined in the code, not in JSON like item flags) after updating the branch from upstream.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/957bc179-9889-442e-93d2-9621b5f40012)
