### ISSUE TITLE
Unable to escape the Lab in the Lab Start scenario.

### ISSUE THREAD

**Issue by NobleJake** [cataclysmbnteam/Cataclysm-BN#4598]
### Describe the bug

https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2759#issue-1696769560

![20240507_141438](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/108422062/f5023dc6-137c-437c-88a5-7f19cf22fed6)
IIRC the scientist ID card in the lab reward room were confirmed to be generated like the screenshot above, allowing players to escape when playing the lab start scenario, but since the lab finale rework this doesn't seem to be the case, so players can't play the lab start scenario normally.

### Steps To Reproduce

1. Select a lab startup scenario.
2. arrive at lab finale.
3. but since the lab finale revamp, scientist ID cards are not generated, so it is impossible to escape outside the lab.

### Versions and configuration

android version, May 5

**Comment by Soadreqm** [comment]
Note that you can also find an ID card on a zombie scientist, disarm and move one of the teleporter pads, find a handheld teleporter, find the required books to craft an electohack, find high explosives capable of breaking the door, find a connection to the subway system, or find and install one of several CBMs that can be used to open, bypass or break the doors.

**Comment by NobleJake** [comment]
Well, there might not be a subway, there might not be a room with a teleporter, there might not be an ID card from a scientist zombie, and even if you do find a CBM, you're forced to have the skill level or mutation to apply it, and it's extremely unlikely that you'll find a specific CBM that lets you walk through a wall or use a hydraulic lifter. I don't think relying on these RNG to escape was the original intent.

**Comment by chaosvolt** [comment]
The microlabs at least aren't a problem because last I checked you can't start in those, at least in vanilla. Those don't even have finales. I agree that all the finales likely should have a card as insurance against weird RNG. I might see if I can check the finales and fix any missing cards later today.

In practice the finale keycard is technically the absolute last resort, since any character that can pass the combined filters of "can survive whatever's in the finale to loot it" and "can get past the turrets to reach the card reader at the entrance" can survive just about anything else a lab can throw at you, so they'd have free rein to explore the lab to find much less risky options to escape with.
