### ISSUE TITLE
Crash when creating world + inability to name worlds ( [Curses] experimental 2024-06-xx,tested up to experimental 2024-05-30)

### ISSUE THREAD

**Issue by SilearFlare** [cataclysmbnteam/Cataclysm-BN#4816]
### Describe the bug

Tried downloading the latest experimental (curses, linux, x64) game says 0x9 (tab) is an invalid character and stops me from generating a world. Tested experimental curses linux x64 version from 2024-05-30, the bug does not show up and world can be created safely, so it happened in the last couple weeks.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/5557920/9114e9a1-02b4-4633-b2ee-174681dec734)

This happens with any kind of world, this is what happens when I get a randomly generated name by just moving forward with worldgen. Throws an 0x9 character error, deletes one character from the world's name, refuses to continue. 
If I continue to press tab to continue, it eventually reaches this stage where it actually breaks into the console's prompt for world name `(world nam :)`
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/5557920/7d349c5d-d9a0-4207-9e34-aedc001958d9)

### Steps To Reproduce

look

### Versions and configuration

up

**Comment by fakepass** [comment]
I have also encountered this bug (also curses, linux, very recent self-compiled game) and did some poking around. It seems the issue here is that the world name prompt, when presented with a character that does something special (in this case, tab) appends that character to the world name *in addition* to doing whatever it is that character should do. Pressing tab appends a tab character to the world name, then checks whether the world name is valid before trying to finish things and shows you that error message because you're not allowed to put tabs in a world name.

When I rebound world creation to x, it just appended x to the name before asking me whether I was sure.

The function in question is, I believe, worldfactory::show_worldgen_tab_confirm, which I believe calls string_input_popup::query_string to handle input. I cannot truthfully say I understand either function well enough to feel comfortable editing them.

**Comment by fakepass** [comment]
I recompiled the game and can still reproduce the bug.
![Screenshot from 2024-07-03 01-13-56](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/8741119/4b225a6f-2f97-4599-97c6-d361d430d4df)

**Comment by scarf005** [comment]
could you check whether latest changes are pulled? could you specify the commit the build is based on?

**Comment by fakepass** [comment]
Yes, I have of course pulled the latest changes. I'm on commit 8beb2d58ee9f904fe4ca43fd911848a26532d04b and this is reflected on the title screen.

**Comment by fakepass** [comment]
Also, the bug doesn't happen if the world name is already the maximum possible length.

**Comment by scarf005** [comment]
> Yes, I have of course pulled the latest changes. I'm on commit 8beb2d58ee9f904fe4ca43fd911848a26532d04b and this is reflected on the title screen.

i'm sorry, but the screen is borderless and doesn't seem to contain commit hash

**Comment by fakepass** [comment]
Oh, I didn't mean in the screenshot; the commit hash is obscured by the world creation screen there. Here's a new screenshot.
![Screenshot from 2024-07-03 03-04-24](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/8741119/a3bf71aa-2341-45df-847b-9d8d5147ab7c)

**Comment by SilearFlare** [comment]
I can likewise confirm the bug persists after #4918, I'm using the latest experiemental release from [e95f6098e05bb61219af53d3b9179fe8716e18b2](https://github.com/cataclysmbnteam/Cataclysm-BN/commit/e95f6098e05bb61219af53d3b9179fe8716e18b2) and I'm still getting the same error when generating a random world with a random name.
![woops](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/5557920/464e3800-50f2-4595-ace1-bcf67e9303be)

**Comment by SilearFlare** [comment]
How to trigger it? It's pretty simple, I thought I had written the explanation in the opening pretty concisely
I can't speak for fakepass since he seems to be using windows, but in my case, simply downloading a version of BN from June (we'll use[ the latest version here for reference](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/download/2024-07-03/cbn-linux-curses-x64-2024-07-03.tar.gz)) of the curses version of cataclysm and literally trying to make any world will incur in the bug. I could go through the tedious and time onerous process of pinpointing specifically which release causes this crash, so we may pinpoint the offending commit but I hoped it would not come to that. The dang thing just happens as easily as running the program and trying to make a world for me. Any world. In fact, the game would segfault if I tried to bypass name finalization of world generation and just use go "play now!".

**Comment by chaosvolt** [comment]
I see that now, yes. The confusion only really came because I was told that porting that DDA PR would fix this, which turned out to be false information because the bug it tackled was in fact something completely different, and I'm now not even sure if the bug it set out to fix was even one that affected BN in the first place.

Apologies for that.

**Comment by scarf005** [comment]
Cannot reproduce in tiled linux.

```
OS: KDE neon jammy 22.04 x86_64
Host: Victus by HP 15L Gaming Desktop TG02-0xxx
Kernel: Linux 6.5.0-41-generic
Uptime: 15 hours, 26 mins
Packages: 2500 (dpkg), 525 (nix-user), 48 (nix-default), 37 (flatpak-user)
Shell: fish 3.7.1
Display (LG HDR QHD): 2560x1440 @ 60Hz [External]
Display (Odyssey G52A): 2560x1440 @ 165Hz
DE: KDE Plasma 6.1.2
WM: KWin (Wayland)
WM Theme: Breeze
```

**Comment by SilearFlare** [comment]
Yes, specifically seems to be a curses issue, we specified this in both our posts. Not a tiles issue. Do you wish for me to edit the issue name specifically to reflect the name to "curses experimental"? :question:

**Comment by KheirFerrum** [comment]
Still awaiting confirmation from @scarf005 of both this issue and that the fix I made works.

**Comment by scarf005** [comment]
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/ba931b45-3c29-4c66-ac25-307a0defac0e)

can confirm it's reproducible.
