### ISSUE TITLE
Helicopter eats insane amount of fuel

### ISSUE THREAD

**Issue by Firestorm01X2** [cataclysmbnteam/Cataclysm-BN#486]
Helicopter eats insane amount of fuel. It smust be review and fixed. 
Fuel consumption could be potentially reduced 10 times or even more

https://github.com/cataclysmbnteam/Cataclysm-BN/pull/481#issuecomment-824273265

>  Coolthulhu commented 3 days ago
> Holy shit that chopper drains its fuel faster than if all its tanks were wrecked. It's less of a vehicle and more of an immobile fuel tanker with two good engines to scavenge. It spawns with tons of fuel.

Note: look here: 
https://github.com/SpadeDraco/useful_helicopters
https://github.com/DrPariah/useful_helicopters

**Comment by olanti-p** [comment]
The 2-seated one at top speed (410 km/h, or 5 submaps/turn) consumes 30L/turn.
That's 16 seconds of flight with full tanks.

**Comment by Coolthulhu** [comment]
Lots of weird stuff:
* Their minimum fuel usage during acceleration is at 70 mph because realism. The player isn't informed of that.
* They idle at 100% engine load. This is separate from fuel consumption due to acceleration.
* The formula for engine load (in 0.1% of max) during acceleration with a heli is this:
```
            if( velocity_kt < 70 ) {
                value = 49 * std::pow( velocity_kt, 3 ) -
                        4118 * std::pow( velocity_kt, 2 ) - 76512 * velocity_kt + 18458000;
            } else {
                value = 1864 * std::pow( velocity_kt, 2 ) - 272190 * velocity_kt + 19473000;
            }
            value *= 0.0001;
            load = std::max( 200, std::min( 1000, ( ( value / 2 ) + 100 ) ) );
```
* The above formula depends entirely on velocity, not acceleration, meaning that it's optimal to "pulse" it rather than going at steady velocity

Heli code is a mess that needs a proper redesign.

**Comment by Coolthulhu** [comment]
After the change, helicopter fuel consumption is pretty reasonable.
