### ISSUE TITLE
Crazy Party no longer spawns private resort starts

### ISSUE THREAD

**Issue by Relgar** [cataclysmbnteam/Cataclysm-BN#5015]
### Describe the bug

Crazy Party starts no longer are able to find private resorts. I'm not sure why.

### Steps To Reproduce

1. Try a crazy party start.
2. Get below error. Retrying multiple times does not help.

### Screenshots

![image](https://github.com/user-attachments/assets/e6f457e8-0e8c-4612-9237-a19aa5ec0149)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: 011b3e3 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    Teleportation [teleportation_tech],
    Jackledead Armory [jackledead_armory],
    Mythical Martial Arts [MMA],
    Aftershock - Easydocs [AFS_Easydocs],
    Manual Bionic Installation [manualbionicinstall],
    No Addictions [No_Addictions],
    No Filthy Clothing [no_filthy_clothing],
    No Jacking [no_jacking],
    No Lifting Reqs [disable_lifting],
    Prevent Zombification [no_zombify],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by RoyalFox2140** [comment]
By the way all specific location scenarios have had random failures with finding a location for years. It's usually fairly rare though unless you're doing extremely specific starts like this.

**Comment by chaosvolt** [comment]
Best one really can do for the most part is tinker with the overmap special's placement settings to make them more forgiving about what range of city sizes and distances, in my experience. My guess is check how it differs from mansion spawns if at all, and start by changing their city stats to match mansions for any property that was previously more restrictive than mansions. Total spawnability will still be lower since there are multiple types of mansion overmap special entries, whereas resorts will likely be an overmap-unique spawn with only one variant.
