### ISSUE TITLE
Items with lockpicking quality are not used first when trying to open locked metal doors

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#5028]
### Describe the bug

If you have an improvised lockpick, a crowbar and a toolbox in your inventory and try to open a closed metal door.

It first tries the crowbar, if you drop the crowbar and try again, it'll use the toolbox (probably due to prying? quality?).

If you then drop the toolbox it'll correctly use the improvised lockpic to open the closed metal door.

### Steps To Reproduce

1. Have lockpick, crowbar and toolbox in invetory
2. Try open metal door
3. Fail
4. ???
5. Don't profit

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: a7b5922 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots],
    Elevated bridges [elevated_bridges],
    Teleportation [teleportation_tech],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    PKs Rebalancing [PK_REBALANCE],
    Secronom [secronom],
    Secronom+ Lore Expansion [secronom_lore_expansion],
    C.R.I.T. Expansion [crt_expansion],
    Sierra Madre [sierra_madre],
    Bio-Synth Robot expansion [gekkobots],
    Nechronica Redux [Nechronica_Redux],
    The Arcology Mod [arcology],
    Really Dark Skies [realdarkskies],
    Arcana and Magic Items [Arcana],
    Magical Nights [MagicalNights],
    Manic Magical Nights [ManicMagicalNights],
    Project: Pack Rat [Jake's_Squirrel_mod],
    Add Bandits Extended+ [GOV_BANDITS_KAI_R],
    NPC Increased Location Spawns Combined [npc_increased_location_comb],
    More Bandits, Testing version [More_Bandits],
    More Dangerous Encounters [More_Dangerous_Encounters],
    Morlock Village [morlock_village],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/C.R.I.T. Patchmod [Arcana_Crit_Patch],
    Arcana/Magical Nights Patchmod [Arcana_MagiclalNights_Patch],
    Really Dark Skies plus Arcana [realdarkskies_Arcana_patchmod],
    Really Dark Skies plus Cataclysm++ [realdarkskies_CATA_patchmod],
    Really Dark Skies plus PKs Rebalancing [realdarkskies_PK_REBALANCE_patchmod],
    Really Dark Skies plus Secronom [realdarkskies_secronom_patchmod],
    Really Dark Skies plus C.R.I.T. [realdarkskies_CRIT_patchmod],
    Really Dark Skies plus Bio-Synth Robot Expansion [realdarkskies_gekkobots_patchmod],
    Really Dark Skies plus Morlock Village [realdarkskies_morlock_village_patchmod],
    Really Dark Skies plus Magical Nights [realdarkskies_MagicalNights_patchmod],
    Really Dark Skies with reviving Xenoids [realdarkskies_reviving_xenoids],
    Even More Mutations [even_more_mutations],
    Mutant NPCs [mutant_npcs],
    Psychiclysm [psychiclysm],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Salvaged Robots [Salvaged_Robots],
    Bug's life [Bug's life],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    DinoMod [DinoMod],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Really Dark Skies plus DinoMod [realdarkskies_Dino_patchmod],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - Mods Extension [MMA_Mods_Extension],
    Wield Wild Weapons [WIELD_WILD_WEAPONS],
    Thog's Things [Thogs_Things],
    Tankmod: Revived [Tankmod_Revived],
    Valik's Machine Shop 1.1 [valikengines],
    Thog's Vehicles Standalone [Thogs_Vehicles],
    Really Dark Skies plus Thog's Vehicles [realdarkskies_Thogs_Vehicles_patchmod],
    CDDA Variety Pack [ks_variety_pack],
    Merchant Mod [Merchant],
    Hydroponics [hydroponics],
    Wandering Masters [wandering_masters],
    Expanded Archery [ExArch],
    MST Extra [MST_Extra],
    Makeshift Items Mod [makeshift]
]

**Comment by remmark99** [comment]
This is my first time checking the games code, but I think that happens because metal door has examine action set as "locked_object" which first tries to use prying tool, and only then a lockpicking one, instead of "locked_object_pickable" which goes for lockpicking first:
(https://github.com/cataclysmbnteam/Cataclysm-BN/blob/f5a0677b9d94c40ed9d17f299f8e531973a462cf/data/json/furniture_and_terrain/terrain-doors.json#L2313)](https://github.com/cataclysmbnteam/Cataclysm-BN/blob/f5a0677b9d94c40ed9d17f299f8e531973a462cf/data/json/furniture_and_terrain/terrain-doors.json#L2322C1-L2322C39)
The fix would probably to simply change this line to "locked_object_pickable", but I guess prying is usually faster and more convenient and that's why it's set this way. Tho I do remember that you sometimes get to pick what you want to do with a door.

**Comment by RoyalFox2140** [comment]
And another part of this issue, it should not allow you to use worn hairpins and fancy hairpins for lockpicking. If an item with tool qualities is worn as clothing and not inside a holster/toolbelt it should disallow using it in situations where it may get destroyed.

**Comment by chaosvolt** [comment]
If no one tackles this I might mess with it, possibly alongside making locked display cases pickable, tomorrow.

**Comment by chaosvolt** [comment]
Okay so I found a problem here: `locked_object_pickable` flat-out doesn't even allow you to use a prying tool at all, if you drop your lockpick I found that doors set to use that examine object leave you pining for

Re-reading the OP tells me that locked doors as they are now still freely use lockpicks OR crowbars, which is entirely as expected. I misread this at first and mistakenly assumed that only one tool was being permitted. So the root issue here is the code doesn't give you any sane way to prioritize which tool to use.

I'd close this as invalid except there is a legit flaw in the logic for it. If you have a prying tool, but it lacks the quality to actually work on the door you're targeting, it isn't smart enough to skip the futile attempts to pry and instead go straight to lockpicking:
![image](https://github.com/user-attachments/assets/2cf1ad85-83c2-40b3-9689-77274bab9237)

**Comment by chaosvolt** [comment]
So, I see three potential fixes here:
1. Just swap it so the player will try to lockpick a door first, pry it open second. That would avoid this fuckery I encountered of "having a crowbar prevents you from even attempting" very elegantly but I dunno if players will be okay with that or not.
2. Have it still try to pry first, but first check that the pry attempt would fail outright due to lack of quality, skip trying to pry outright if so, then come BACK to a pry attempt anyway after checking for lockpicks just so that we can still print the "your tool sucks too much bro"
3. Since the above method would already require duplicating crowbar iuse code in the examine action to actually work (or moving parts of the iuse to a "calculate if you can do X" function that both can cite), an even more complicated but potentially ideal solution would be to create a function that determines whether lockpicking or prying currently has the highest success rate (automatically putting prying in last place if the best tool can't pry the targeted door) then automatically make you do the most successful action.

**Comment by Unrepentant-Atheist** [comment]
I'd go with 1. probably performance-wise the best option. And lockpicks are dime-a-dozen and crafted quickly. And high-end lockpicks, reinforced are often mid to late game, and don't break that quick.

**Comment by chaosvolt** [comment]
Another idea that came up was making it favor prying if you're standing up and lockpicking if you're crouching, which would also be fairly easy to add in and of itself but run into the issue of whether I'd still want to bother trying to make it automatically skip prying if it'd be softlocked by prying difficulty, vs. just trying to explain to the player to crouch if they want to lockpick first...
