### ISSUE TITLE
Nailboard trap can be made with 20 glue and zero nails

### ISSUE THREAD

**Issue by DoubleBullfrog** [cataclysmbnteam/Cataclysm-BN#5074]
### Describe the bug

![image](https://github.com/user-attachments/assets/cc5a4162-ac49-4d49-9778-426ba15d41e5)
You shouldn't be able to substitute glue for nails in a nailboard trap. When building directly from raw components, it should specifically require 18 nails and separately 2 glue or nails.

### Steps To Reproduce

Build a nailboard trap out of 20 glue, 3 planks, and zero nails.

### Versions and configuration

Current experimental, windows 10.

**Comment by RoyalFox2140** [comment]
This is a very fast fix but also will be a very annoying one due to scope. When @Lamandus allowed glue to substitute nails in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4698 It must've accidentally happened due to crafting standards inheriting. The reason this is annoying is because now every recipe using the new craft standard has to be checked. Specifically any recipes using "nail_glue"

**Comment by Lamandus** [comment]
I fixed the nailboard itself but but the nailboard_trap. on it
