### ISSUE TITLE
Soldier Zombies Nigh-Immune to Explosives

### ISSUE THREAD

**Issue by narkiel** [cataclysmbnteam/Cataclysm-BN#5082]
### Is your feature request related to a problem? Please describe.

An unintended consequence of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4738,  **feat(balance): shrapnel deals ballistic damage #4738**, has resulted in Soldier Zombies and similar being nearly immune to player explosives.

To recreate:
1. Visit an area where soldier zombies congregate; the searchlights in front of a FEMA camp are a great demonstration.
2. Throw a frag grenade into the crowd.
3. Repeat 5 or 6 times
4. Observe that few, if any, zombies have died.

One would reasonably expect that a grenade blowing up a zombie should destroy it, and seriously inconvenience nearby zombies, even if they are wearing MBR vests.  Much less a barrage of grenades.

### Describe the solution you'd like

Possible solutions, in approximate most-to-least-recommended order:
1. Implement Armor Coverage for zombies
2. Boost Shrapnel damage and implement a damage falloff with distance, such that a zombie standing on a grenade is not just hit by *more* shrapnel but  shrapnel that can penetrate his armor
3. Give shrapnel Armor Penetration, to represent the fact that shrapnel travels much faster than a typical bullet
4. Tally up all the Shrapnel damage in a round and then apply the Armor reduction only once, rather than per-shrapnel-piece
5. Some kind of dirty hack like making zombies take double damage from shrapnel

**Comment by chaosvolt** [comment]
Dang, that's...annoying, yeah. Not sure what the best fix is.

**Comment by chaosvolt** [comment]
So I might in this case want to audit the ballistic protection of soldier zombies, but on the other hand I'm wondering if some simulation of armor coverage would be better. That'd be code work however. Either way I'd still want it so that having a ceramic MBR vest makes it easier for the player to survive shrapnel, but it shouldn't make zombies immune too.

**Comment by narkiel** [comment]
I believe DDA already has armor coverage for zombies. If that's the road we want to pursue, it would probably be easier to just port the feature over from them.

**Comment by chaosvolt** [comment]
I know they have a weakpoint system but I'd have to check whether that applies to explosion and fragment code too. That might be a dead-end since DDA still exclusively uses the old "define explosion power in grams of TNT and define fragments by their casing mass and frag size" code, while BN mostly uses the ability to explicitly set desired damage.

**Comment by chaosvolt** [comment]
I'll want to tinker with this a bit more to see if it will be reasonable balance-wise to make it possible for a direct grenade blast to one-shot a zombie soldier, but for now they should be decent odds of a two-shot.
