### ISSUE TITLE
Mark t_floor as wooden floor

### ISSUE THREAD

**Issue by AlecWhite** [cataclysmbnteam/Cataclysm-BN#5111]
### Is your feature request related to a problem? Please describe.

Currently `t_floor` doesn't convey to the player that it is a wooden floor. Just a vague and ambiguous "floor".

### Describe the solution you'd like

Change the name of the "floor" to "wooden floor".
![floor](https://github.com/user-attachments/assets/dbcd4b66-5041-4c48-be6f-861663a4bc77)

**Comment by RoyalFox2140** [comment]
Wooden Walls and Walls both exist which makes that complicated, I don't know what we're going to call Walls because they're plastered and painted. Our construction code calls them Standard Wall and also seems to not take paint or plaster which makes this even weirder as the costs of Wood Wall and "Standard Wall" are extremely identical. We also can't remove either, wood walls are for cabins and standard walls are for modern homes.

**Comment by scarf005** [comment]
maybe we could rename them `{adjective|noun} wooden wall`? e.g `plastered wooden wall`
