### ISSUE TITLE
Extended/Retractable Claws weirdness

### ISSUE THREAD

**Issue by DoubleBullfrog** [cataclysmbnteam/Cataclysm-BN#5164]
### Describe the bug

Retractable Claws cannot be extended, Extended Claws are considered a separate mutation that you can mutate despite already having Retractable Claws, and you can have Claws and Retractable Claws at the same time. It's a big mess.

### Steps To Reproduce

Inject a lot of feline serum and watch your mutations. When you get Extended Claws, retract them, and you can't extend them again.

### Screenshots

![image](https://github.com/user-attachments/assets/93cb1337-b1fd-4572-9f66-f465d5a0466a)
![image](https://github.com/user-attachments/assets/d41db4ad-7e05-4911-8493-7bdbbb0f72f9)
![image](https://github.com/user-attachments/assets/58c7e5f1-2ad3-478e-947d-f04d1d6b60d6)

### Versions and configuration

Windows 10 - 89d56e9 - Tiles - English - Default Mods

**Comment by chaosvolt** [comment]
Looks like the actual root problem here is Extended Claws is in the obsolete folder but still has the feline category because it copies from the base version: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/main/data/json/obsoletion/mutations.json#L72

Question is which implementation is desired I suppose. From the JSON it looks like retractable claws already automatically provides an unarmed damage bonus with no penalty, so extended claws is likely obsoleted because it was decided that it'd be a better idea to just let the player automatically benefit from them passively instead of forcing the player to manually turn their claws on and off.

Reasonable, since I don't see any hand encumbrance or clothing restrictions on the active version that would make sense to let the player toggle on and off, nor is the damage bonus for the claw mutation even really high enough to justify giving it such drawbacks when extended, balance-wise.

**Comment by DoubleBullfrog** [comment]
That makes sense and is a lot easier to fix. Extended Claws just needs the copy_from removed and any necessary lines manually added in.
