### ISSUE TITLE
cataclysm-tiles: Exec format error lin32-tiles

### ISSUE THREAD

**Issue by winorun** [cataclysmbnteam/Cataclysm-BN#558]
cataclysmbn-1918-lin32-tiles.tar.gz release compiled for 64 bit.

~~~
./cataclysm-tiles 
bash: ./cataclysm-tiles: не удаётся запустить бинарный файл: Ошибка формата выполняемого файла
~~~

~~~
./cataclysm-launcher 
./cataclysm-launcher: 48: exec: ./cataclysm-tiles: Exec format error
~~~

**Comment by olanti-p** [comment]
What's your OS?
Just tested `1918-lin32-tiles`and `1918-lin64-tiles` on 64 bit Kubuntu 20.04, both work fine.

**Comment by winorun** [comment]
>> cataclysmbn-1918-lin32-tiles.tar.gz release compiled for 64 bit.

You test on 64 bit.

What for?

My OS is 32 bit

**Comment by winorun** [comment]
I compiled cataclysm-tiles for 32 bit 

[cataclysmbn-1918-lin32-tiles](https://drive.google.com/file/d/12yU7s67FmMuFlDu6_n31KJ6T_iM3LT_W/view?usp=sharing)

**Comment by olanti-p** [comment]
Ah, sorry, I misunderstood what you meant. After some testing in vm can confirm that `lin32` releases, despite being named x32, were actually compiled for x64.
![image](https://user-images.githubusercontent.com/60584843/125824202-11e2c68f-d798-459a-a968-36f2e77dd29d.png)
![image](https://user-images.githubusercontent.com/60584843/125824703-964f40d8-b857-4dcb-b983-fd21ac3495cd.png)

We've had to migrate build system a month ago (#609), and `lin32` releases were dropped along the way, so this issue is not relevant anymore. There are no plans on dropping `win32` or `lin64` though, so compiling `lin32` from source is still an option and should remain such for the foreseeable future.
