### ISSUE TITLE
Place of CBMs in Bright Nights should be clarified.

### ISSUE THREAD

**Issue by Firestorm01X2** [cataclysmbnteam/Cataclysm-BN#57]
# Place of CBMs in Bright Nights should be clarified
Considering CBM I've read that complains from players:
1) A lot CBM really usefull early in the game. At the point you actually able to access them - you don't really need them anymore.
2) Going to dagnerous locaton to unergo surgery to install simple CBMs sounds like really bad idea.

I can add my own complains to that:
1) Current CBM intallation process looks needlesly overcomplicated (dirty cbms, anesthetic kits, sterilizing, packing) and restrics player from interesting game mechanics.
2) https://github.com/CleverRaven/Cataclysm-DDA/issues/27826 (CBM install chances using Autodoc must be revised)

Aftershock solved it that way:
https://github.com/CleverRaven/Cataclysm-DDA/pull/42202
Looks like in aftershock bionic slots are enabled, but installing/uninstalling CBMs realively easy process. Hower it is only one of the options.

There is also questions : 
1) What to do with manual bionics installations? 
2) What to do with bionic slots system?
3) What to do with ridrt CBMs?

**Comment by Coolthulhu** [comment]
> What to do with manual bionics installations?

I don't have a complete idea yet, but so far I see it like this:
* Installing a bionic requires performing a couple of rolls, each with increased pain
* If allied NPC is nearby, best chance for each roll is used
* Autodoc is just a fake allied NPC, possibly with insta-success on a set number of rolls
* Number of failures determines outcome: no problems, infection, mutations, bionic getting faults, installation fails, bionic wrecked. Possibly more than one, so that you can fail so hard you install a burnt-out faulty bionic which is worse than useless.
* Harder bionics require more rolls
* Remove filthy bionics, instead of spawning filthy, they get alien-themed faults, like giving you a bad/neutral mutation (not removable as long as bionic is there), hunger increase, deals damage/pain/nausea when it uses power etc.

So basically, easy bionics are installable by hand, hard ones are still installable but best with friends, zombie-extracted ones are common but always flawed.

> What to do with bionic slots system?

Needs rebalancing first, then it can be enabled.

* Power storage bionics cost slots. There is no artificial limit on power storage.
* Every bionic should have a reason to be installed and a reason not to be installed (other than the effort of installing it). Possible example: strength bionic, dexterity bionic and monoblade sharing too many slots to install all 3 of them.
* Combat bionics shouldn't share slots with utility ones, such as crafting, food, lockpick etc.
* Any bionic that can be replaced by carrying an item should be removed or cost 0 slots
* Currently slots are based on limbs, but if there was a good system that doesn't use limbs, I could disconnect slots from limbs
* (Optional) Possibility of going over the limit, at the cost of faults and mutations that are permanent as long as slots are over the limit

**Comment by Firestorm01X2** [comment]
What to do with anesthetic kits for Autodoc. Looks like Aftershock removes, for example. Maybe BN shoud get rid of them too?

**Comment by Coolthulhu** [comment]
Removal is fine, though they could be repurposed as a knockout toxin.

**Comment by MrOlaf** [comment]
Bionics installation in Aftershock was reworked in likeness of the Caves of Qud system for cybernetics. IMO it is a good solution, because you want to encourage the player to try new things instead of the (in)famous CDDA-balance, which makes everything obsolete by the time a player can use it due to fail chances and buggy mechanics (like hot air and insulating clothing). Right now bionics make a difference for choosing a starting profession, but are almost obsolete when you get them and the ability and opportunity to install them mid-game. It should be a positive *OH SH*T. AWESOME! * moment when player sees an autodoc, not an *OH SH*T, I need food,water,books,cbms and a month of in-game time to get a high tier bionic installed without a 70% fail chance".

**Comment by Coolthulhu** [comment]
The "question" in the issue is answered. The issue is known and being discussed.
Proposals regarding individual, well-defined changes can be made, but I don't see much benefit from having such broad issues with unclear scope.
