### ISSUE TITLE
Please update version magiclysm

### ISSUE THREAD

**Issue by Altogolik** [cataclysmbnteam/Cataclysm-BN#588]
# Is your feature request related to a problem? Please describe.
The belugling version of this cool mod is very old, I do not want to play DDA so please update the mod 

# Describe the solution you'd like
We need new buildings, classes, items, magic 

# Additional context
Make magic great again

**Comment by ZhilkinSerg** [comment]
Your best chance is to start doing this yourself - copy latest version of Magiclysm from CDDA repo, try creating world with it and fix (or at least document) any errors that would popup.

**Comment by Altogolik** [comment]
> Your best chance is to start doing this yourself - copy latest version of Magiclysm from CDDA repo, try creating world with it and fix (or at least document) any errors that would popup.

Cool, you can do it now. I will wait (๑•̀ㅁ•́ฅ)  the developers told me that it would be difficult, but I believe in you!

**Comment by Mom-Bun** [comment]
Hey sorry to disappoint you, but it is highly unlikely magiclysm will be updated

1.  The current maintainer KorGgent has zero interest in the bright nights build, and is fully interested in DDA, so all his focus and energy on magiclysm is focused there, not here
2. Any other developers or regular contributors as far as I know have shown no interest in porting latest Magiclysm 
3. Porting the changes from DDA to BN isn't that simple, there is a lot of underlying code, conflict, and issues that you'll have to solve, the majority of the magic code for example in BN is out of date compared to DDA so the majority of the new things in DDA will unlikely added to BN unless you figure out how to add the code in a way Coolthulhu approves

For all intents and purposes, both Magiclysm and Aftershock are bitrot in the BN fork currently, as none of the active maintainers have shown interest to take the effort to port all these things over, and this isn't coming from a place of "Oh I dislike BN" because I am an Aftershock maintainer, and I wanted to update aftershock for BN, however it required to set up a unique and new workflow, solve several different conflicts, figure out what code is needed and what isn't, and remove things that will not be supported like pockets (which'll feature prominently in the future in Aftershock, and I bet magiclysm as well)

So the only choice for playing up to date magiclysm is well... play dda for its mods, or learn C++ and github and figure out how to the port the code and mods yourself, sorry.

**Comment by ZhilkinSerg** [comment]
> > Your best chance is to start doing this yourself - copy latest version of Magiclysm from CDDA repo, try creating world with it and fix (or at least document) any errors that would popup.
> 
> Cool, you can do it now. I will wait (๑•̀ㅁ•́ฅ) the developers told me that it would be difficult, but I believe in you!

No, you.

**Comment by DrPariah** [comment]
Some of the things could be kitbashed or converted to BN, but it would require workarounds for hard-coded stuff. New buildings, npcs, suchlike, time consuming but possible to convert. The Attunement system, as is, takes/requires hard-code, but could be brought over as a more general spell type setup. Other stuff? Unsure.
If you haven't tried, and you really are sincere and not just trolling, give it a crack and see if you can bring over some of the JSON based stuff.

**Comment by chaosvolt** [comment]
Having been asked about this suggestion in discord DMs by the issue opener, I'll give my thoughts on it here.

Put simply, it will be slow going. It's not just the JSON that needs to be ported over. There's a lot of hardcode support that will need to be ported over as well. The problem with this is twofold:
1. It will need a keen eye to sort out, fix, and test any code differences caused by the steady divergence between DDA and BN. Anything that interacts with nested container behavior (which is a deceptively wide varieity of interactions), for example.
2. The spell and relic code will need extensive bug-testing even if step one goes smoothly. There are a lot of minor oddities and non-functional bits that will need to be checked for and quashed.

I've been asked to do it, but I'm reluctant to port over anything that isn't a bugfix for features already in BN. I'm still not very experienced with C++ and offline matters has given me less time and energy to tackle large projects like that, so I wouldn't be the best person for this.

**Comment by Altogolik** [comment]
Thanks for the answers, I went to version of DDA, I study the new version of Magiclysm. The content is straight much more, and the Aftershok is still updated too. I hope you ever update it all on BN. I will ask the familiar translator to help with the translation of Arcane MOD. (may want)

**Comment by Coolthulhu** [comment]
Known issue, but solving it requires significant dev time.

Closing as stale
