### ISSUE TITLE
controlled monster

### ISSUE THREAD

**Issue by Bitaryit** [cataclysmbnteam/Cataclysm-BN#620]
When fighting a monster swarmer, a "controlled monster" appears on the character in the effects. 

# Steps To Reproduce

1. Create a character.
2. Summon the swarmer monster (there are many types of them, 2 from the beginning)
3. Fight him in close combat.

# Expected behavior

When fighting swarmer, no controlled monster effect appeared. 

# Screenshots
![image](https://user-images.githubusercontent.com/86398561/123214110-7e775280-d4cf-11eb-9968-066e48f73d5d.PNG)

# Versions and configuration

**Comment by olanti-p** [comment]
"Swarmer" monster is from Secronom mod, we have nothing to do with it.
I believe @Kenan2000 is the current maintainer of BN version over at https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack.

Anyway, "Controlled Monster" effect is harmless to the character, so you can probably ignore it. There _is_ an issue with it as it does not wear off as it should, but that's going to be fixed in #638.

Ideally mods should be able to use `copy-from` with effect_types to fix stuff like this.

**Comment by olanti-p** [comment]
Update: concidentally alpha swarmers have been disabled some hours before I wrote that
https://github.com/Kenan2000/Secronom-Zombies/commit/5cabfb003c54be8ea9d02f6783a674efe49d1b5d
So this should no longer be a problem.
