### ISSUE TITLE
Release procedure update

### ISSUE THREAD

**Issue by nanohard** [cataclysmbnteam/Cataclysm-BN#673]
Having just one branch to upload changes to has the potential to break the game at any time.
Having a separate branch for stable (`main`) will allow semantic (or other) version tagging for proven stable releases.
A branch for testing would allow players to report any unforeseen consequences of changes before it's pushed to stable for the masses.

I would also recommend a `freeze` branch taken from testing that only gets updated once per X days, and in turn `main` would also get updated once per X days. This `freeze` branch would be the "experimental" build that early-adoption players would use.

# Describe the solution you'd like
1. Rename `upload` branch to `main` or `stable`
2. Add `testing` or `dev` or `unstable` branch
3. Add `freeze` branch, taken from `testing`/`dev`/`unstable` once per X days. After X days of no major issues, push to `main`/`stable`

# Describe alternatives you've considered
Ignore the branch name `upload`, but I cannot; it gnaws at my mind as a creature from the nether, scratching at the same spot slowly, maliciously, until the darkness peeks through in attempt to drive me mad. The creature, black as ink, eyes and teeth white as quartz, perpetually smiling as it scratches, scratches, always scratching until the hole gapes and it reaches for my face, laughing and smiling, that perfect, impossibly white smile.

**Comment by scarf005** [comment]
hi, sorry for the necroposting. personally, I prefer trunk-based workflow, because it encourages
- short-lived feature branches
- quick development
- clean git history via squash merges

for stable and frozen releases, this role can be largely replaced with tags, albeit at the cost bug hotfix cannot be backported, but this could be solved by releasing stables more often (i'm thinking of `YYYY-mm` versioning scheme)

> Rename `upload` branch to `main` or `stable`

100% agree. I also dislike this unfortunate branch name and would like to change it asap. however we need to take consider of existing PRs and forks, so it might take a while.
