### ISSUE TITLE
[Feature] Sit Boon / Standing Bane

### ISSUE THREAD

**Issue by nanohard** [cataclysmbnteam/Cataclysm-BN#677]
Would be nice to get some sitting vs standing checks for Read, Eat, Sew, etc. Anything where people would normally sit.
Should take a look at `rigid table manners` trait to see how it's done and possibly copy that format since it's already implemented, rather than inventing a new, slower way of doing it.

**Comment by Coolthulhu** [comment]
Rigid table manners was done badly because it requires you to position exactly at the spot you have to be on, rather than checking for it in `PICKUP_RADIUS`.
It's one of the reasons I removed it. The other was that it was a negative trait that wasn't negative enough to warrant its cost, while also being tedious to work with.

A proper way to implement this would be like this:
* In `activity_type`, add a field that describes if the activity can benefit from sitting. Load it in `activity_type::load`. Similar to how `rooted` is handled.
* In `player_activity::start`, for activity types that benefit from sitting, find the best sitting place within radius (see `try_fuel_fire`). Print appropriate message, like "You sit on the bed" or "You sit on the dirt. It's not very comfortable...".
* In `player_activity::do_turn`, for activity types that benefit from sitting, apply the bonus from sitting.
* (Optionally) Have the character actually walk to the spot when starting the activity, then back after ending it.

It's not very hard, but certainly not trivial either. At the moment, comfort values are written only for sleep, in `Character::base_comfort_value`.
Adding specific sitting comfort values would require another field in `furn_t`, something like `sitting_comfort`.
Eating won't be able to benefit, as it's not a long activity.

As for actual sitting bonus:
* If it's a morale bonus, it should accumulate rather than apply immediately. That is, it should be staged it in time with `calendar::once_every`.
* Having it provide rest would be too complex at the moment, since rest is used for HP and sleep deprivation healing, and could make it harder to fall asleep later.
* Bonus to crafting would be a bit "unrealistic" without designating which crafts can benefit and which can't.

**Comment by nanohard** [comment]
Ah, no wonder I could find no reference to `TABLEMANNERS` lol
Thanks for the info, that helps a ton.

Maybe a slight bane to eating if not on a furniture tile?
Agreed on crafting, but would like to see it on sewing specifically if I can.

**Comment by Coolthulhu** [comment]
Closing as stale
