### ISSUE TITLE
[Request] Skill and stat training equipment

### ISSUE THREAD

**Issue by Kaylakaze** [cataclysmbnteam/Cataclysm-BN#696]
# Describe the solution you'd like
It'd be nice if various items in the world could be used to train stats and skills. For example, weight benches could train strength, punching bags could train unarmed, a wooden man could train Wing Chun, targets could train archery, etc. XP should be lower than books and, similar to books, have a minimum and maximum, though they should probably have a much larger space between the two and possibly a morale bonus/malus.

**Comment by Coolthulhu** [comment]
Training skills with items might be a thing in the future.
The idea is to make them similar to recipes, basically "recipe that levels up archery" or other skill.

Stat grinding won't happen.

**Comment by Kaylakaze** [comment]
Any particular reason you're so adamant against the stat increases? It makes sense to me that if one found themselves in the Cataclysm, they'd want to start training to be stronger and faster. 
Obviously, I don't think these would be "use it for 4 hours and a stat goes up" sort of thing. To do it without any major system changes, I'd say each hour training would increase the stat by a random amount between maybe 0.01 and 0.05.
It'd be adding more mechanics, but it'd make sense to even limit it, such as a) you can't stat train while in pain and b) you can only train for X hours in a 24 hour period (X being determined by your current stat level and increasing as it does) without getting inflicted with pain and c) if you try to use pain killers to exercise past that point, the pain continues to build until it starts causing HP damage.

**Comment by Coolthulhu** [comment]
> Any particular reason you're so adamant against the stat increases?

* Sounds grindy
* Makes the game easier later on while not helping early on. Front-loaded difficulty is a problem.
* Mutations and stat-boosting CBMs would lose importance

Temporary stat boosts from being well fed or drugs can happen.
Permanent stat boosts for surviving enough days - as a level up of sorts - might happen.

Permanent stat boosts from spending total of 50 hours on "working out" activity is what I'm against.

**Comment by Kaylakaze** [comment]
> * Sounds grindy

I don't see how "use jump rope for an hour" as part of a character's daily routine is any more grindy than "spend seven hours making biodiesel", "spend an hour cooking a meal", "spend two hours building a fence", or "read for twelve hours". (New idea just in: Maybe add a +X 24-hour morale boost for "Worked out today" and, if that morale boost exists or is a certain level, prevent the character from working out again, thus placing a limit on working out without any major system changes or adding new attributes to the PC)

> * Makes the game easier later on while not helping early on. Front-loaded difficulty is a problem.

As time goes by, the monsters mutate and get stronger while the player never changes, making the character relatively WEAKER as the game goes on in the current implementation. While it doesn't help front-loaded difficulty, it does mean a character that starts out terrible isn't condemned to suck forever.

> * Mutations and stat-boosting CBMs would lose importance

Mutations and stat-boosting CBMs are nearly impossible to get on a character without the right stats, meaning you're required to spec in a certain way if you want to survive to even see those. Not to mention the RNG makes them something that's more of a happy accident when you get them and not something you can really plan for any time in the early to mid game and even late game they're a problem (and talk about grindy). Plus, if the max level of a stat that an exercise item can grant is limited, it INCREASES the value of mutations and CBMs because those items become the only way you can exceed the normal human limits. If I have 5 STR, a mutation that gives me a +2 STR bonus still leaves me a terrible character and that +2 becomes practically worthless (both a STR 5 and a STR 7 character is walking zombie food). If I can get that +2 STR bonus and then work out until I'm at 12 STR natural (which, let's say, is the max you can train on a weight bench), that extra +2 STR from the mutation pushing me to 14 STR becomes very important.

**Comment by Coolthulhu** [comment]
> I don't see how "use jump rope for an hour" as part of a character's daily routine is any more grindy than "spend seven hours making biodiesel"

It's not, but I don't want to add grind to places where it was absent from before. At the moment, the only way to grind stats is to grind mutagen, which is one of the things that I'm slowly reworking to be less grindy.

> As time goes by, the monsters mutate and get stronger while the player never changes, making the character relatively WEAKER as the game goes on in the current implementation.

Stat-wise yes, but the equipment gains more than makes up for it. At least for most of the game.

> While it doesn't help front-loaded difficulty, it does mean a character that starts out terrible isn't condemned to suck forever.

This is an argument, but I don't consider it strong enough to offset the downsides.
I want to include base stats in mutation potential calculations, so that challenge characters will eventually gain better mutations to offset their bad stats.

> Mutations and stat-boosting CBMs are nearly impossible to get on a character without the right stats

Mutations aren't stat-dependent. Intelligence helps with book reading, but book reading is a very slow way to grind. It's faster to gather ingredients for high-skill recipes.
You don't need intelligence to learn book recipes.
In BN, at the moment, you are guaranteed to install CBMs, they just get downsides when you get bad rolls. The stat dependent parts are extraction from corpse and removing downsides after low-skill+stat installation.

> Plus, if the max level of a stat that an exercise item can grant is limited, it INCREASES the value of mutations and CBMs because those items become the only way you can exceed the normal human limits.

But decreases value of starting with a stat above normal values. Say, you start with 12 and boosts can only get you +5, but 19 and 17 don't differ that much.
Starting with stats as low as 5 means you're either doing a challenge or a very focused build. If you're doing a challenge, training would kinda miss the point. If you're doing a focused build, training would remove the "focussedness".

I don't see a good way of integrating stat training in the system.
Maybe as a "perk" from gaining high skill in some particular category. For example, if you reach lvl 8 bashing weapons, you get to choose between permanent +2 str or applying long-term "concussion" debuff on bashing crit (just examples).

**Comment by Kaylakaze** [comment]
>It's not, but I don't want to add grind to places where it was absent from before. At the moment, the only way to grind stats is to grind mutagen, which is one of the things that I'm slowly reworking to be less grindy.

Be careful when trying to reduce "grind" in a game because you can end up optimizing away the entire game. Where would The Sims (one of the largest selling game franchises of all time) be without grind? Practically the entire game is nothing but grind. And then there's WoW. Or Animal Crossing. Or any one of hundreds of mobile titles these days. The difference is, you have to make it advantageous to not just keep spamming the same thing over and over (or at least fun to do so). For example, if I want to train my electronics skill early, I can make a firestarter, take it apart, make a new one, take it apart, etc until I'm not gaining skill anymore. That grind isn't fun. I can grind my survival at low levels though by walking through the woods and foraging everything. That's still not great, but it's better, because I'm exploring while grinding and gathering resources I can use later. 

Of course, that's moot if you limit exercise to a few hours per day, since then you're not grinding at all. I may make a PR adding a jump rope or something that demonstrates how exercising could be done (without including stat-boosting code) without it being grindy. 

> Stat-wise yes, but the equipment gains more than makes up for it. At least for most of the game.

Only if you can survive long enough to get that equipment in the first place. And if you have the STR to carry it.

> Mutations aren't stat-dependent. Intelligence helps with book reading, but book reading is a very slow way to grind. It's faster to gather ingredients for high-skill recipes.

Mutations and CBMs are stat-dependent in that you need the stats to be able to get to them in the first place. If you don't spec at least 10 STR and 9 DEX at the start, your character might as well be a challenge run character.

> Starting with stats as low as 5 means you're either doing a challenge or a very focused build. If you're doing a challenge, training would kinda miss the point. If you're doing a focused build, training would remove the "focussedness".

But the idea is that you're role-playing as a character at the beginning of the Cataclysm. If I'm playing as a character that was a scientist before the cataclysm, I'd take low physical stats and high INT. That doesn't mean that the character is INT focussed, just that "this is who the character was before the Cataclysm" and that character should have to (and be able to) evolve to meet their new circumstances. If that makes things slightly easier for some players in the late game, so what? That's their choice to use the mechanic or not. Just like it's their choice to play an anti-post-humanist and refuse to use CBMs and mutagens. Just like it's our choice to reduce mutation rates and zombie speed, and a whole mess of other options that can make things easier. (For example, I made a mod to get rid of the new medical zombies because I didn't like them and feel they're OP and far too common). Personally, I'd like to be slaughtering zombies by the dozen in the late game, with only the strongest eldritch horrors able to stand up to me, because that's just how role-playing games work, but I want to work my way there, not just start off giving myself max stats or severely nerfing my opposition. If the late game isn't hard enough, you make it harder by adding more and greater challenges, not by nerfing the player.

As a severely out-of-shape web developer IRL and I can guarantee you that if there was a zombie apocalypse, once I was relatively safe, I would be spending every day working to lose weight and increase my strength and endurance.

> I don't see a good way of integrating stat training in the system.
> Maybe as a "perk" from gaining high skill in some particular category. For example, if you reach lvl 8 bashing weapons, you get to choose between permanent +2 str or applying long-term "concussion" debuff on bashing crit (just examples).

We already have stat increases through the StatsThroughSkills and StatsThroughKills mods. I was just looking for a more role-play-focused solution.

**Comment by Coolthulhu** [comment]
> For example, if I want to train my electronics skill early, I can make a firestarter, take it apart, make a new one, take it apart, etc until I'm not gaining skill anymore. That grind isn't fun.

It would be more fun if it took less time, but rarer components that need to be found.
Stat grinding sounds much more likely to be "repeat grind procedure" than "find rare stuff to improve stat".

> Of course, that's moot if you limit exercise to a few hours per day, since then you're not grinding at all.

Then it becomes a daily chore and a "long term grind", which can get even worse due to tedium.
In the end, the result is the same: after x days, you have +y to stat and spend z hours on getting it.

> Only if you can survive long enough to get that equipment in the first place.

Unless the jump rope gave massive stats early on, it wouldn't boost early game survivability much.

> And if you have the STR to carry it.

Unless you pick challenge tier low str, bad back or mutate into a mouse, only the heaviest stuff will even get near carrying capacity.
Or if you carry a ton of junk, but that's a bad habit.

> If you don't spec at least 10 STR and 9 DEX at the start, your character might as well be a challenge run character.

I've done 8/8/8/14 runs just fine. They weren't strong characters, but could mutate, scavenge labs, clear hospitals.
CBMs are rare right now, but I intend to push them earlier into game, so that they stop being endgame only stuff.

> But the idea is that you're role-playing as a character at the beginning of the Cataclysm.

That's a personal challenge. I can add support for those when it's "objectivizable", but I will not balance the game around players choosing their own subjectively graded playstyles, because that's simply impossible.

> That's their choice to use the mechanic or not.

I guess if someone implemented a "stats through training" mod, I'd be fine with it.
Things that get into the core have stricter standards. Here, "just don't use it" doesn't cut it. I try to balance the core around default settings, multi-pool chargen, no mods, player who will use every option at his disposal to win. In the future, also player who wants to win fast (slower options would get buffs).

> If the late game isn't hard enough, you make it harder by adding more and greater challenges, not by nerfing the player.

Not adding an option that buffs the player through grind isn't nerfing. So far, I mostly buffed the player (bows, explosions, grab break) and added challenge in the form of medical zombies and higher default zombie evolution speed.

I do intend to add harder zones, but at the moment, it's hard to split them from easier ones. Zombie evolution is global, mapgen is independent from global position, specials get "pushed around" making it impossible to get a precise distribution of them.
I don't want to pad specials with warning turrets, I'd rather add directionality to mapgen, with "hard biomes". But this is not done yet.

> We already have stat increases through the StatsThroughSkills and StatsThroughKills mods.

Yes, but those are not balanced and are grindy. Stats through perks could get grindy without a skill gain rework, but after a skill gain rework, which I have plans for, it might be non-grindy.


So far it sounds like something that would be fine in a mod, but I don't see it in current core.
Later, if the core changes enough, I'd consider merging it into core, but again: core would need to change in a way that makes them "work" together.
