### ISSUE TITLE
Recipe with no primary skill can have booklearn difficulty above 0

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#721]
Book learn is only usable if a recipe meets one of the requirements:
* Has a primary skill
* Difficulty is set to 0 (`"skills_required"` can still be set higher)
* Booklearn difficulty is explicitly set to 0

Some mods, notably cata++, have recipes that don't meet any of the requirements above. This produces recipes that can't ever be used.
There should be a warning in this case. There is one for `decomp_learn`.

**Comment by chaosvolt** [comment]
That should now be fixed on Cata++'s end, though old releases for DDA's stable builds will retain the wonky recipes. Oh well. Having some way to mitigate the problem would be handy though. Ignoring the difficulty of skill-less recipes could be an alternative failsafe method, but eh.

Probably better to encourage modders to not do that since it's almost certainly not going to be intentional.
