### ISSUE TITLE
Butter, cheese, and obtaining them

### ISSUE THREAD

**Issue by saltmummy626** [cataclysmbnteam/Cataclysm-BN#883]
# Is your feature request related to a problem? Please describe.
With some play time, investigation, and discussion, it turns out that the process involved in making butter is needlessly convoluted while also having it's recipe restricted to a single book. Meanwhile, the recipes involved in making cheese are relegated to several... survival books or one very specific cooking book and require very specific sets of ingredients.

The issue this brings about is that of "why." Not just why are they so resource intensive, but why bother at all? There are foods or alternatives that are much easier and more rewarding to get. To obtain butter, you must process raw milk into a "rising cream jar" from 12 units of milk and a 3l jar. After that, you wait until that "rising cream jar" has turned into a "milk cream jar, and extract the heavy cream from the jar with a recipe, and then process that heavy cream into raw butter using a tool with "churning quality 1." The raw butter created will last for 1 week unless processed further into ghee, which is also ridiculous as butter has a surprisingly long shelf life even outside of refrigeration. All of this can be done only if you have learned the recipes involved with the book "Things to do with milk." This whole process is needlessly tedious.

With cheese, it is a similar but much simpler set of circumstances. Cheese is created by creating "curdling milk," waiting until it becomes "curdled milk," and then adding salt via the crafting menu. The issue with this is much less of a hassle than butter, except for the ingredients. If you are not using herbs for the second ingredient, making the curdling milk relies on either coincidental obtaining of the ingredients, or the possession of cattle so that getting a hold of the stomachs necessary to make the cheese the only really time sensitive part of the process. While writing up this issue, I'm coming to the realization that my issues with the cheese process are probably not as big a deal as the butter is... Still though, butter should not take more steps than _cheese._

# Describe the solution you'd like
For butter, I recommend simplifying the process. Remove all the steps between milk and butter, and make butter a recipe you can learn through adequate knowledge of cooking. Chaosvolt suggested in discussion on discord upgrading the churns "churn quality" instead of removing it and adding "churn quality 1" to things like jars so that the jar method could be used. Milk+salt+churn for a quick and efficient recipe and a simple "Milk+salt+container" recipe for a long/slow low yield process. Also, make the recipe appear in more books and/or make it a recipe learnable through experience in the cooking skill. I mean, seriously, my class made butter in second grade with mason jars, salt, and the pure unlimited autistic energy that only children are capable of expending.
**EDIT**
I would also suggest combining "butter" and "raw butter" into a single item as having two kinds of butter which both do exactly the same thing (except one has less nutritional value for some reason?) is redundant. Further, extending the shelf life on butter from one week to one month, and add the ability to seal it up in jars for preservation. Why a month? That's the longest time I've kept butter on my counter for before running out of butter. Covered of course. 

For cheese, I recommend simplifying the recipe. Currently, it requires 3 vinegar, any number of "rennet" ingredients, and milk. add the vinegar to the list of possible "rennet" ingredients instead of it being a separate ingredient. I was going to suggest lowering the requirement for reading one of the books needed to learn the recipe, but increasing the range of books the recipe appears in might be a better idea.

# Describe alternatives you've considered
I have not considered any alternatives to the butter stuff since what I've suggested is, I feel, the most straightforward and least tedious solution.

Cheese I have considered simply leaving it as is. The recipe as is can be fairly straight forward depending on the situation. Part of me also wishes to keep cheese as a late game food item. When I first played Cataclysm ages ago, grilled cheese was considered the top of the tops in terms of food wealth since cheese was difficult to keep fresh back then and it couldn't be made. It also had a vast mood buff attached to it.

# Additional context
IRL, butter is usually made using heavy cream. I know for a fact though, since I've done it both when younger and as an adult, that you can just use unpasteurized milk and a little salt. Hell, I've bought local unpasteurized milk with butter clinging to the lid as a result of the bottles getting shaken around in transit, no salt required. Milk comes out of the cow in game as "raw" milk, and I see no reason why we can't use the fresh product for making butter.

**Comment by chaosvolt** [comment]
The rough thoughts I had during discussion of this prior to opening the issue:
1. The recipe chain definitely needs to be simplified. Heavy cream and buttermilk seem more or less superfluous, but ideally whatever items don't have any other recipe use should be removed first.
2. There'd be two ways to handle butter churns vs. atomic butter churns, jars, etc. The method as you mentioned would be for deployed butter churns to have churning 2 as well, giving churning 1 to various containers, and thus splitting the recipes up into slowly making butter with churning 1 vs. making butter with churning 2.

An alternative would be to save churning 2 for the atomic churn and have it be used in a recipe that makes regular butter, maybe even a secondary recipe for ghee if you're feeling spicy, having churning 1 be used to make either butter or raw butter directly from milk and whatever else is needed, then have a secondary recipe for raw butter that uses any valid 

Exact implementation would depend on whether you'd prefer butter churns make butter or raw butter, of course. Having wooden churns make regular butter makes atomic butter churns comparatively less useful (though letting it make ghee mitigates this), while having wooden butter churns make raw butter makes said wooden churns less useful relative to the jar method (aside from time saving).

3. Sanity-check autolearning and book learning. I think that raw butter should probably have an autolearn at 1-2 cooking levels higher than its difficulty, optionally with survival as a sub-skill. Cookbooks and Autobiography of a Mountain Man should be alternative booklearns for, while low-level chemistry books could be given alternative booklearns for the jar method. Butter and ghee via atomic churing probably would be full autolearn since it's just learning to use a tool that, from its description, probably has some level of basic instructions printed on the device (alongside enough safety warnings to give you second thoughts about doing so).

4. Making hard cheese less annoying to craft in terms of material cost would be a definite plus. Vinegar being needed separate from other rennet sources is probably an oops on my part from as far back as when I first added the recipes to MST, so making it count as another source of rennet seems good. Maybe tone the wild herb requirement down to 10-20? As for autolearn, probably 2-3 levels above its difficulty, again possibly with some survival as a subskill. For booklearns I'd need to double-check what books it can already be learned from.

5. Aside from adding an autolearned "ghee from atomic butter churn" recipe, ghee could possibly be autolearned at 2-3 levels above its difficulty, but more important would be to add the ability to booklearn the standard recipe to more cookbooks. Clarified butter is used outside of India, after all.

**Comment by saltmummy626** [comment]
The only issue I see with your response is that, unless I'm missing something, there is no atomic butter churn. It's either from Aftershock, or a feature in a newer version of BN I haven't downloaded yet.

**Comment by chaosvolt** [comment]
Small update, Salt pointed out the atomic butter churn is actually an Aftershock item, so the worry of regular churns competing with it is less of a problem. It'd still be good to flesh out what niche it has via also doubling as a cooking tool to clarify butter, however.

**Comment by saltmummy626** [comment]
Now that you mention it, what exactly is the functional difference between "raw" butter and butter? Would it be prudent simply to combine the items or is there something that can only be made with raw butter or vice versa?

**Comment by chaosvolt** [comment]
From looking at it, raw butter seems to have no salt and is made purely from turning raw milk into a cream jar (somehow taking 6 hours to magic it into a complete jar), then make heavy cream from that, then churn into raw butter.

I can't see how you even craft regular butter.

**Comment by saltmummy626** [comment]
I believe regular butter is "found" butter. Stuff that you can scavenge in grocery stores and whatnot. It has an expiration of two weeks. Raw butter on the other hand expires after one week. The expiration and your above  observation have brought something I should add to this issue to mind. Standby for edit.

**Comment by chaosvolt** [comment]
So, working on a general plan for what to do to implement the intended simplification...


For butter:
1. Drop the distinction between raw butter and regular butter.
2. Implement a basic recipe for producing butter directly from raw milk (possibly also milk), using a source of any container quality and some salt. This recipe could be autolearned, with booklearns from various relevant books. Buttermilk as a by-product can be kept if it has any worthwhile uses, otherwise obsolete it too. The heavy cream step can be abstracted away as some extra time, depending on point three.
3. If any extra uses can be thought up for heavy cream, we could keep the step of making a cream jar. Otherwise, obsolete heavy cream entirely.
4. Add a separate recipe for making butter more efficiently with a butter churn. Otherwise same basic concept as the manual method, possibly booklearn-only and with more survival-focused book selection.
5. Atomic butter churns in Aftershock are silly, and their current use is largely pointless. If we don't obsolete them, maybe have them used in a recipe to make ghee directly from milk, implying that the atomic churn also heats the milk during processing to clarify it.
6. Make sure that production of butter has sane use of calories, charges, and such to hit the intended target nutrition per unit of butter.

For cheese: 
1. Add a recipe for farmer's cheese, green cheese, paneer, whatever you want to call it. Milk or raw milk, vinegar, some salt, boiling and relevant cheesemaking tools. Basically makes fresh soft cheese made directly from milk without using rennet. Simple enough it could be autolearned.
2. Allow said farmer's cheese to be smoked into hard cheese, as this is simpler and more logical to autolearn than making aged rennet-based cheese. Include both smoking entry in the item definition and a recipe using charges of a smoker, as is normal for smoking food.
3. Sanity-check calories, yield, and charges of both types of cheese. Probably 5 charges per stack for both, 20% yield for curds so 5 charges of milk plus 1 charge of vinegar would yield 5 charges of fresh cheese. Each charge of cheese should have about the same calories as 1 charge of milk as a result. Likewise hard cheese should be 5 charges, calories can stay unchanged.
4. If we keep the other method of making cheese, it needs some reworking to better fit making large batches of cheese more efficiently. Drop the vinegar requirement from curdling milk, it already uses a source of rennet. Optionally add an actual rennet item made by drying stomachs and mixing with water, so a fresh stomach isn't such a blocker for production. This production chain can stay booklearn-only so long as smoking green cheese is autolearned.
