### ISSUE TITLE
open up temperature and spoilage information to the player

### ISSUE THREAD

**Issue by RaynaWasTaken** [cataclysmbnteam/Cataclysm-BN#987]
# Is your feature request related to a problem? Please describe.
Its currently nor really possible to observe how outside temperature or refridgerators/freezers and similar affect food spoilage.
It would be nice to have a way for the player to see how tile temperature affects spoilage rate of items, either on the item itself (spoiled by date on room temperature vs spoiled by date on current temperature)
Or alternatively, let the player be able to inspect tile temperature directly, also printing an information in a way of "Spoiling rates are reduced by x% due to temperature)

# Describe the solution you'd like
See above

# Describe alternatives you've considered
change cooling furniture and terrain features to reduce item spoilage by a set percentage thats ideally mentioned in its tooltip in some way shape or form, either by a seperate value, or simply in text.
Ideally, this value would also be jsonized so modded items can take advantage of it

**Comment by Coolthulhu** [comment]
I'm closing because of #2267
I do like the idea of having +% rot speed, but right now, the numbers are rather volatile at higher temperature.
Instead, I went with "with current conditions, it's guaranteed to last at least x". For normal conditions, it's shelf life divided by almost 6 - that's how high it goes.
